// 乐理数据表（从 app/page.tsx 抽出）：音级映射 / 和弦类型 / 音程 / 音阶模式 / 显示名称

export const NOTES = ["C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯", "A", "A♯", "B"]
export const NOTES_FLAT = ["C", "D♭", "D", "E♭", "E", "F", "G♭", "G", "A♭", "A", "B♭", "B"]

export const DEGREE_TO_SEMITONE: Record<string, number> = {
  "1": 0, "b2": 1, "2": 2, "#2": 3, "b3": 3, "3": 4, "4": 5,
  "#4": 6, "b5": 6, "5": 7, "#5": 8, "b6": 8, "6": 9,
  "#6": 10, "b7": 10, "7": 11, "maj7": 11, "bb7": 9,
  "b9": 1, "9": 2, "#9": 3, "b13": 8, "13": 9, "11": 5, "#11": 6
}

// Chord types with intervals - 完整62种和弦类型，与SOLO保持一致

export const CHORD_TYPES = [
  // 三和弦类 (6种)
  { name: "Major", intervals: [0, 4, 7], symbol: "", group: "triad", groupName: "Triads", groupZh: "三和弦" },
  { name: "Minor", intervals: [0, 3, 7], symbol: "m", group: "triad", groupName: "Triads", groupZh: "三和弦" },
  { name: "Dim", intervals: [0, 3, 6], symbol: "dim", group: "triad", groupName: "Triads", groupZh: "三和弦" },
  { name: "Aug", intervals: [0, 4, 8], symbol: "aug", group: "triad", groupName: "Triads", groupZh: "三和弦" },
  { name: "sus2", intervals: [0, 2, 7], symbol: "sus2", group: "triad", groupName: "Triads", groupZh: "三和弦" },
  { name: "sus4", intervals: [0, 5, 7], symbol: "sus4", group: "triad", groupName: "Triads", groupZh: "三和弦" },
  
  // 加音和弦 (4种)
  { name: "add9", intervals: [0, 4, 7, 14], symbol: "add9", group: "add", groupName: "Add Chords", groupZh: "加音和弦" },
  { name: "madd9", intervals: [0, 3, 7, 14], symbol: "madd9", group: "add", groupName: "Add Chords", groupZh: "加音和弦" },
  { name: "6add9", intervals: [0, 4, 7, 9, 14], symbol: "6/9", group: "add", groupName: "Add Chords", groupZh: "加音和弦" },
  { name: "m6add9", intervals: [0, 3, 7, 9, 14], symbol: "m6/9", group: "add", groupName: "Add Chords", groupZh: "加音和弦" },
  
  // 减和弦类 (2种)
  { name: "dim7", intervals: [0, 3, 6, 9], symbol: "dim7", group: "dim", groupName: "Diminished", groupZh: "减和弦" },
  { name: "dimMaj7", intervals: [0, 3, 6, 11], symbol: "dim(maj7)", group: "dim", groupName: "Diminished", groupZh: "减和弦" },
  
  // 六和弦类 (2种)
  { name: "6", intervals: [0, 4, 7, 9], symbol: "6", group: "six", groupName: "Six Chords", groupZh: "六和弦" },
  { name: "m6", intervals: [0, 3, 7, 9], symbol: "m6", group: "six", groupName: "Six Chords", groupZh: "六和弦" },
  
  // 属七和弦类 (18种)
  { name: "7", intervals: [0, 4, 7, 10], symbol: "7", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7b5", intervals: [0, 4, 6, 10], symbol: "7♭5", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7#5", intervals: [0, 4, 8, 10], symbol: "7♯5", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7b9", intervals: [0, 4, 7, 10, 13], symbol: "7♭9", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7#9", intervals: [0, 4, 7, 10, 15], symbol: "7♯9", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7#11", intervals: [0, 4, 7, 10, 18], symbol: "7♯11", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7b13", intervals: [0, 4, 7, 10, 20], symbol: "7♭13", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7#5b9", intervals: [0, 4, 8, 10, 13], symbol: "7♯5♭9", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7#5#9", intervals: [0, 4, 8, 10, 15], symbol: "7♯5♯9", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7b5b9", intervals: [0, 4, 6, 10, 13], symbol: "7♭5♭9", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7b5#9", intervals: [0, 4, 6, 10, 15], symbol: "7♭5♯9", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7b9b13", intervals: [0, 4, 7, 10, 13, 20], symbol: "7♭9♭13", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  { name: "7alt", intervals: [0, 4, 8, 10, 13, 15, 20], symbol: "7alt", group: "dominant", groupName: "Dominant 7th", groupZh: "属七和弦" },
  
  // 属九和弦类 (4种)
  { name: "9", intervals: [0, 4, 7, 10, 14], symbol: "9", group: "dominant9", groupName: "Dominant 9th", groupZh: "属九和弦" },
  { name: "9b13", intervals: [0, 4, 7, 10, 14, 20], symbol: "9♭13", group: "dominant9", groupName: "Dominant 9th", groupZh: "属九和弦" },
  { name: "9#11", intervals: [0, 4, 7, 10, 14, 18], symbol: "9♯11", group: "dominant9", groupName: "Dominant 9th", groupZh: "属九和弦" },
  { name: "9sus4", intervals: [0, 5, 7, 10, 14], symbol: "9sus4", group: "dominant9", groupName: "Dominant 9th", groupZh: "属九和弦" },

  // 属十一和弦类 (1种)
  // 补登记：getChordDegrees 的 extendedChordMap 里一直有 '11' 的度数序列、
  // DISPLAY_NAMES 四个模式段与 i18n 的 chord_11 也都有，唯独 CHORD_TYPES 漏了 ——
  // 于是那条度数序列不可达（函数开头 `if (!chordType) return ["1"]` 先返回），
  // iReal 导入的 `11` 也只能退到 `9`。
  { name: "11", intervals: [0, 4, 7, 10, 14, 17], symbol: "11", group: "dominant11", groupName: "Dominant 11th", groupZh: "属十一和弦" },
  
  // 属十三和弦类 (4种)
  { name: "13", intervals: [0, 4, 7, 10, 14, 21], symbol: "13", group: "dominant13", groupName: "Dominant 13th", groupZh: "属十三和弦" },
  { name: "13b9", intervals: [0, 4, 7, 10, 13, 21], symbol: "13♭9", group: "dominant13", groupName: "Dominant 13th", groupZh: "属十三和弦" },
  { name: "13#9", intervals: [0, 4, 7, 10, 15, 21], symbol: "13♯9", group: "dominant13", groupName: "Dominant 13th", groupZh: "属十三和弦" },
  { name: "13#11", intervals: [0, 4, 7, 10, 14, 18, 21], symbol: "13♯11", group: "dominant13", groupName: "Dominant 13th", groupZh: "属十三和弦" },
  
  // 大七和弦类 (8种)
  { name: "Maj7", intervals: [0, 4, 7, 11], symbol: "maj7", group: "major7", groupName: "Major 7th", groupZh: "大七和弦" },
  { name: "maj7#5", intervals: [0, 4, 8, 11], symbol: "maj7♯5", group: "major7", groupName: "Major 7th", groupZh: "大七和弦" },
  { name: "maj7#11", intervals: [0, 4, 7, 11, 18], symbol: "maj7♯11", group: "major7", groupName: "Major 7th", groupZh: "大七和弦" },
  { name: "maj7b6", intervals: [0, 4, 7, 11, 8], symbol: "maj7♭6", group: "major7", groupName: "Major 7th", groupZh: "大七和弦" },
  { name: "maj7#9", intervals: [0, 4, 7, 11, 15], symbol: "maj7♯9", group: "major7", groupName: "Major 7th", groupZh: "大七和弦" },
  
  // 大九和弦类 (4种)
  { name: "Maj9", intervals: [0, 4, 7, 11, 14], symbol: "maj9", group: "major9", groupName: "Major 9th", groupZh: "大九和弦" },
  { name: "maj9#11", intervals: [0, 4, 7, 11, 14, 18], symbol: "maj9♯11", group: "major9", groupName: "Major 9th", groupZh: "大九和弦" },
  { name: "maj9#5", intervals: [0, 4, 8, 11, 14], symbol: "maj9♯5", group: "major9", groupName: "Major 9th", groupZh: "大九和弦" },
  { name: "maj9b6", intervals: [0, 4, 7, 11, 14, 8], symbol: "maj9♭6", group: "major9", groupName: "Major 9th", groupZh: "大九和弦" },
  
  // 大十三和弦类 (3种)
  { name: "maj13", intervals: [0, 4, 7, 11, 14, 21], symbol: "maj13", group: "major13", groupName: "Major 13th", groupZh: "大十三和弦" },
  { name: "maj13#11", intervals: [0, 4, 7, 11, 14, 18, 21], symbol: "maj13♯11", group: "major13", groupName: "Major 13th", groupZh: "大十三和弦" },
  { name: "maj13#5", intervals: [0, 4, 8, 11, 14, 21], symbol: "maj13♯5", group: "major13", groupName: "Major 13th", groupZh: "大十三和弦" },
  
  // 小七和弦类 (8种)
  { name: "m7", intervals: [0, 3, 7, 10], symbol: "m7", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  { name: "m7b5", intervals: [0, 3, 6, 10], symbol: "m7♭5", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  { name: "m7b5nat9", intervals: [0, 3, 6, 10, 14], symbol: "m7♭5(9)", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  { name: "m7b6", intervals: [0, 3, 7, 10, 8], symbol: "m7♭6", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  { name: "mMaj7", intervals: [0, 3, 7, 11], symbol: "m(maj7)", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  { name: "mMaj9", intervals: [0, 3, 7, 11, 14], symbol: "m(maj9)", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  { name: "mMaj13", intervals: [0, 3, 7, 11, 14, 21], symbol: "m(maj13)", group: "minor7", groupName: "Minor 7th", groupZh: "小七和弦" },
  
  // 小九和弦类 (2种)
  { name: "m9", intervals: [0, 3, 7, 10, 14], symbol: "m9", group: "minor9", groupName: "Minor 9th", groupZh: "小九和弦" },
  { name: "m9b5", intervals: [0, 3, 6, 10, 14], symbol: "m9♭5", group: "minor9", groupName: "Minor 9th", groupZh: "小九和弦" },
  
  // 小十一/十三和弦类 (3种)
  { name: "m11", intervals: [0, 3, 7, 10, 14, 17], symbol: "m11", group: "minor11", groupName: "Minor 11th/13th", groupZh: "小十一/十三和弦" },
  { name: "m13", intervals: [0, 3, 7, 10, 14, 21], symbol: "m13", group: "minor11", groupName: "Minor 11th/13th", groupZh: "小十一/十三和弦" },
  
  // 挂留和弦类 (5种)
  { name: "7sus4", intervals: [0, 5, 7, 10], symbol: "7sus4", group: "sus", groupName: "Suspended", groupZh: "挂留和弦" },
  { name: "7sus4b9", intervals: [0, 5, 7, 10, 13], symbol: "7sus4♭9", group: "sus", groupName: "Suspended", groupZh: "挂留和弦" },
  { name: "sus4b9", intervals: [0, 5, 7, 13], symbol: "sus4♭9", group: "sus", groupName: "Suspended", groupZh: "挂留和弦" },
  { name: "13sus4", intervals: [0, 5, 7, 10, 14, 21], symbol: "13sus4", group: "sus", groupName: "Suspended", groupZh: "挂留和弦" },
  { name: "13sus4b9", intervals: [0, 5, 7, 10, 13, 21], symbol: "13sus4♭9", group: "sus", groupName: "Suspended", groupZh: "挂留和弦" },
  
  // 增和弦类 (1种)
  { name: "aug7", intervals: [0, 4, 8, 10], symbol: "aug7", group: "aug", groupName: "Augmented", groupZh: "增和弦" },
]


export const INTERVALS = [
  { name: "root", semitones: 0, symbol: "1" },
  { name: "flat2", semitones: 1, symbol: "b2" },
  { name: "two", semitones: 2, symbol: "2" },
  { name: "sharp2", semitones: 3, symbol: "#2" },
  { name: "flat3", semitones: 3, symbol: "b3" },
  { name: "three", semitones: 4, symbol: "3" },
  { name: "four", semitones: 5, symbol: "4" },
  { name: "sharp4", semitones: 6, symbol: "#4" },
  { name: "flat5", semitones: 6, symbol: "b5" },
  { name: "five", semitones: 7, symbol: "5" },
  { name: "sharp5", semitones: 8, symbol: "#5" },
  { name: "flat6", semitones: 8, symbol: "b6" },
  { name: "six", semitones: 9, symbol: "6" },
  { name: "flat7", semitones: 10, symbol: "b7" },
  { name: "bb7", semitones: 9, symbol: "bb7" },
  { name: "seven", semitones: 11, symbol: "7" },
  { name: "nine", semitones: 14, symbol: "9" },
  { name: "flat9", semitones: 13, symbol: "b9" },
  { name: "sharp9", semitones: 15, symbol: "#9" },
  { name: "eleven", semitones: 17, symbol: "11" },
  { name: "sharp11", semitones: 18, symbol: "#11" },
  { name: "thirteen", semitones: 21, symbol: "13" },
  { name: "flat13", semitones: 20, symbol: "b13" },
]

export const SCALE_MODES = {
  pentatonic: [
    { name: "Major Pentatonic", notes: [0, 2, 4, 7, 9], intervals: ["1", "2", "3", "5", "6"], formula: "1 2 3 5 6" },
    { name: "Minor Pentatonic", notes: [0, 3, 5, 7, 10], intervals: ["1", "b3", "4", "5", "b7"], formula: "1 b3 4 5 b7" },
    { name: "Dominant Pentatonic", notes: [0, 4, 5, 7, 10], intervals: ["1", "3", "4", "5", "b7"], formula: "1 3 4 5 b7" },
    { name: "Minor 6 Pentatonic", notes: [0, 3, 5, 7, 9], intervals: ["1", "b3", "4", "5", "6"], formula: "1 b3 4 5 6" },
  ],
  majorScaleModes: [
    { name: "Ionian", notes: [0, 2, 4, 5, 7, 9, 11], intervals: ["1", "2", "3", "4", "5", "6", "7"], formula: "1 2 3 4 5 6 7" },
    { name: "Dorian", notes: [0, 2, 3, 5, 7, 9, 10], intervals: ["1", "2", "b3", "4", "5", "6", "b7"], formula: "1 2 b3 4 5 6 b7" },
    { name: "Phrygian", notes: [0, 1, 3, 5, 7, 8, 10], intervals: ["1", "b2", "b3", "4", "5", "b6", "b7"], formula: "1 b2 b3 4 5 b6 b7" },
    { name: "Lydian", notes: [0, 2, 4, 6, 7, 9, 11], intervals: ["1", "2", "3", "#4", "5", "6", "7"], formula: "1 2 3 #4 5 6 7" },
    { name: "Mixolydian", notes: [0, 2, 4, 5, 7, 9, 10], intervals: ["1", "2", "3", "4", "5", "6", "b7"], formula: "1 2 3 4 5 6 b7" },
    { name: "Aeolian", notes: [0, 2, 3, 5, 7, 8, 10], intervals: ["1", "2", "b3", "4", "5", "b6", "b7"], formula: "1 2 b3 4 5 b6 b7" },
    { name: "Locrian", notes: [0, 1, 3, 5, 6, 8, 10], intervals: ["1", "b2", "b3", "4", "b5", "b6", "b7"], formula: "1 b2 b3 4 b5 b6 b7" },
  ],
  melodicMinorScaleModes: [
    { name: "Melodic Minor", notes: [0, 2, 3, 5, 7, 9, 11], intervals: ["1", "2", "b3", "4", "5", "6", "7"], formula: "1 2 b3 4 5 6 7" },
    { name: "Dorian b2", notes: [0, 1, 3, 5, 7, 9, 10], intervals: ["1", "b2", "b3", "4", "5", "6", "b7"], formula: "1 b2 b3 4 5 6 b7" },
    { name: "Lydian Augmented", notes: [0, 2, 4, 6, 8, 9, 11], intervals: ["1", "2", "3", "#4", "#5", "6", "7"], formula: "1 2 3 #4 #5 6 7" },
    { name: "Lydian Dominant", notes: [0, 2, 4, 6, 7, 9, 10], intervals: ["1", "2", "3", "#4", "5", "6", "b7"], formula: "1 2 3 #4 5 6 b7" },
    { name: "Mixolydian b6", notes: [0, 2, 4, 5, 7, 8, 10], intervals: ["1", "2", "3", "4", "5", "b6", "b7"], formula: "1 2 3 4 5 b6 b7" },
    { name: "Locrian Nat 2", notes: [0, 2, 3, 5, 6, 8, 10], intervals: ["1", "2", "b3", "4", "b5", "b6", "b7"], formula: "1 2 b3 4 b5 b6 b7" },
    { name: "Altered", notes: [0, 1, 3, 4, 6, 8, 10], intervals: ["1", "b2", "#2", "3", "b5", "#5", "b7"], formula: "1 b2 #2 3 b5 #5 b7" },
  ],
  harmonicMinorScaleModes: [
    { name: "Harmonic Minor", notes: [0, 2, 3, 5, 7, 8, 11], intervals: ["1", "2", "b3", "4", "5", "b6", "7"], formula: "1 2 b3 4 5 b6 7" },
    { name: "Locrian Nat 6", notes: [0, 1, 3, 5, 6, 9, 10], intervals: ["1", "b2", "b3", "4", "b5", "6", "b7"], formula: "1 b2 b3 4 b5 6 b7" },
    { name: "Ionian Augmented", notes: [0, 2, 4, 5, 8, 9, 11], intervals: ["1", "2", "3", "4", "#5", "6", "7"], formula: "1 2 3 4 #5 6 7" },
    { name: "Dorian #4", notes: [0, 2, 3, 6, 7, 9, 10], intervals: ["1", "2", "b3", "#4", "5", "6", "b7"], formula: "1 2 b3 #4 5 6 b7" },
    { name: "Phrygian Dominant", notes: [0, 1, 4, 5, 7, 8, 10], intervals: ["1", "b2", "3", "4", "5", "b6", "b7"], formula: "1 b2 3 4 5 b6 b7" },
    { name: "Lydian #9", notes: [0, 3, 4, 6, 7, 9, 11], intervals: ["1", "#2", "3", "#4", "5", "6", "7"], formula: "1 #2 3 #4 5 6 7" },
    { name: "Superlocrian bb7", notes: [0, 1, 3, 4, 6, 8, 9], intervals: ["1", "b2", "b3", "3", "b5", "#5", "6"], formula: "1 b2 b3 3 b5 #5 6" },
  ],
  harmonicMajorScaleModes: [
    { name: "Harmonic Major", notes: [0, 2, 4, 5, 7, 8, 11], intervals: ["1", "2", "3", "4", "5", "b6", "7"], formula: "1 2 3 4 5 b6 7" },
    { name: "Dorian b5", notes: [0, 2, 3, 5, 6, 9, 10], intervals: ["1", "2", "b3", "4", "b5", "6", "b7"], formula: "1 2 b3 4 b5 6 b7" },
    { name: "Phrygian b4", notes: [0, 1, 3, 4, 7, 8, 10], intervals: ["1", "b2", "b3", "3", "5", "b6", "b7"], formula: "1 b2 b3 3 5 b6 b7" },
    { name: "Lydian b3", notes: [0, 2, 3, 6, 7, 9, 11], intervals: ["1", "2", "b3", "#4", "5", "6", "7"], formula: "1 2 b3 #4 5 6 7" },
    { name: "Mixolydian b2", notes: [0, 1, 4, 5, 7, 9, 10], intervals: ["1", "b2", "3", "4", "5", "6", "b7"], formula: "1 b2 3 4 5 6 b7" },
    { name: "Lydian Augmented #2", notes: [0, 3, 4, 6, 8, 9, 11], intervals: ["1", "#2", "3", "#4", "#5", "6", "7"], formula: "1 #2 3 #4 #5 6 7" },
    { name: "Locrian bb7", notes: [0, 1, 3, 5, 6, 8, 9], intervals: ["1", "b2", "b3", "4", "b5", "b6", "6"], formula: "1 b2 b3 4 b5 b6 6" },
  ],
  otherScales: [
    { name: "Blues", notes: [0, 3, 5, 6, 7, 10], intervals: ["1", "b3", "4", "#4", "5", "b7"], formula: "1 b3 4 #4 5 b7" },
    { name: "Major Blues", notes: [0, 2, 3, 4, 7, 9], intervals: ["1", "2", "b3", "3", "5", "6"], formula: "1 2 b3 3 5 6" },
    { name: "Diminished Half Whole", notes: [0, 1, 3, 4, 6, 7, 9, 10], intervals: ["1", "b2", "#2", "3", "b5", "5", "6", "b7"], formula: "1 b2 #2 3 b5 5 6 b7" },
    { name: "Diminished Whole Half", notes: [0, 2, 3, 5, 6, 8, 9, 11], intervals: ["1", "2", "b3", "4", "b5", "#5", "6", "7"], formula: "1 2 b3 4 b5 #5 6 7" },
    { name: "Whole Tone", notes: [0, 2, 4, 6, 8, 10], intervals: ["1", "2", "3", "#4", "#5", "#6"], formula: "1 2 3 #4 #5 #6" },
    { name: "Augmented Scale", notes: [0, 3, 4, 7, 8, 11], intervals: ["1", "#2", "3", "5", "#5", "7"], formula: "1 #2 3 5 #5 7" },
  ],
  bebopScales: [
    { name: "Bebop Dominant", notes: [0, 2, 4, 5, 7, 9, 10, 11], intervals: ["1", "2", "3", "4", "5", "6", "b7", "7"], formula: "1 2 3 4 5 6 b7 7" },
    { name: "Bebop Major", notes: [0, 2, 4, 5, 7, 8, 9, 11], intervals: ["1", "2", "3", "4", "5", "b6", "6", "7"], formula: "1 2 3 4 5 b6 6 7" },
    { name: "Bebop Dom7b9b13", notes: [0, 1, 4, 5, 7, 8, 10, 11], intervals: ["1", "b2", "3", "4", "5", "b6", "b7", "7"], formula: "1 b2 3 4 5 b6 b7 7" },
    { name: "Bebop Tonic Minor Melodic", notes: [0, 2, 3, 5, 7, 8, 9, 11], intervals: ["1", "2", "b3", "4", "5", "b6", "6", "7"], formula: "1 2 b3 4 5 b6 6 7" },
    { name: "Bebop Tonic Minor Dorian", notes: [0, 2, 3, 5, 7, 8, 9, 10], intervals: ["1", "2", "b3", "4", "5", "b6", "6", "b7"], formula: "1 2 b3 4 5 b6 6 b7" },
    { name: "Bebop Dorian", notes: [0, 2, 3, 5, 7, 9, 10, 11], intervals: ["1", "2", "b3", "4", "5", "6", "b7", "7"], formula: "1 2 b3 4 5 6 b7 7" },
  ],
  exotic: [
    { name: "Japanese", notes: [0, 1, 5, 7, 10], intervals: ["1", "b2", "4", "5", "b7"], formula: "1 b2 4 5 b7" },
    { name: "Egyptian", notes: [0, 2, 5, 7, 10], intervals: ["1", "2", "4", "5", "b7"], formula: "1 2 4 5 b7" },
    { name: "Spanish Phrygian", notes: [0, 1, 4, 5, 7, 8, 10], intervals: ["1", "b2", "3", "4", "5", "b6", "b7"], formula: "1 b2 3 4 5 b6 b7" },
    { name: "Hijaz", notes: [0, 1, 4, 5, 7, 8, 10], intervals: ["1", "b2", "3", "4", "5", "b6", "b7"], formula: "1 b2 3 4 5 b6 b7" },
    { name: "Double Harmonic", notes: [0, 1, 4, 5, 7, 8, 11], intervals: ["1", "b2", "3", "4", "5", "b6", "7"], formula: "1 b2 3 4 5 b6 7" },
  ],
  symmetrical: [
    { name: "Chromatic", notes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], intervals: ["1", "b2", "2", "b3", "3", "4", "b5", "5", "b6", "6", "b7", "7"], formula: "1 b2 2 b3 3 4 b5 5 b6 6 b7 7" },
    { name: "Augmented", notes: [0, 3, 4, 7, 8, 11], intervals: ["1", "b3", "3", "5", "b6", "7"], formula: "1 b3 3 5 b6 7" },
    { name: "Tritone", notes: [0, 1, 4, 6, 7, 10], intervals: ["1", "b2", "3", "b5", "5", "b7"], formula: "1 b2 3 b5 5 b7" },
  ],
  basic: [
    { name: "Major", notes: [0, 2, 4, 5, 7, 9, 11], intervals: ["1", "2", "3", "4", "5", "6", "7"], formula: "1 2 3 4 5 6 7" },
    { name: "Minor", notes: [0, 2, 3, 5, 7, 8, 10], intervals: ["1", "2", "b3", "4", "5", "b6", "b7"], formula: "1 2 b3 4 5 b6 b7" },
  ],
  church: [
    { name: "Ionian", notes: [0, 2, 4, 5, 7, 9, 11], intervals: ["1", "2", "3", "4", "5", "6", "7"], formula: "1 2 3 4 5 6 7" },
    { name: "Dorian", notes: [0, 2, 3, 5, 7, 9, 10], intervals: ["1", "2", "b3", "4", "5", "6", "b7"], formula: "1 2 b3 4 5 6 b7" },
    { name: "Phrygian", notes: [0, 1, 3, 5, 7, 8, 10], intervals: ["1", "b2", "b3", "4", "5", "b6", "b7"], formula: "1 b2 b3 4 5 b6 b7" },
    { name: "Lydian", notes: [0, 2, 4, 6, 7, 9, 11], intervals: ["1", "2", "3", "#4", "5", "6", "7"], formula: "1 2 3 #4 5 6 7" },
    { name: "Mixolydian", notes: [0, 2, 4, 5, 7, 9, 10], intervals: ["1", "2", "3", "4", "5", "6", "b7"], formula: "1 2 3 4 5 6 b7" },
    { name: "Aeolian", notes: [0, 2, 3, 5, 7, 8, 10], intervals: ["1", "2", "b3", "4", "5", "b6", "b7"], formula: "1 2 b3 4 5 b6 b7" },
    { name: "Locrian", notes: [0, 1, 3, 5, 6, 8, 10], intervals: ["1", "b2", "b3", "4", "b5", "b6", "b7"], formula: "1 b2 b3 4 b5 b6 b7" },
  ],
  minor: [
    { name: "Harmonic Minor", notes: [0, 2, 3, 5, 7, 8, 11], intervals: ["1", "2", "b3", "4", "5", "b6", "7"], formula: "1 2 b3 4 5 b6 7" },
    { name: "Melodic Minor", notes: [0, 2, 3, 5, 7, 9, 11], intervals: ["1", "2", "b3", "4", "5", "6", "7"], formula: "1 2 b3 4 5 6 7" },
  ],
  other: [
    { name: "Blues", notes: [0, 3, 5, 6, 7, 10], intervals: ["1", "b3", "4", "#4", "5", "b7"], formula: "1 b3 4 #4 5 b7" },
    { name: "Whole Tone", notes: [0, 2, 4, 6, 8, 10], intervals: ["1", "2", "3", "#4", "#5", "#6"], formula: "1 2 3 #4 #5 #6" },
    { name: "Diminished", notes: [0, 1, 3, 4, 6, 7, 9, 10], intervals: ["1", "b2", "b3", "3", "#4", "5", "6", "b7"], formula: "1 b2 b3 3 #4 5 6 b7" },
  ],
  bebop: [
    { name: "Bebop Major", notes: [0, 2, 4, 5, 7, 8, 9, 11], intervals: ["1", "2", "3", "4", "5", "b6", "6", "7"], formula: "1 2 3 4 5 b6 6 7" },
    { name: "Bebop Dorian", notes: [0, 2, 3, 4, 5, 7, 9, 10], intervals: ["1", "2", "b3", "3", "4", "5", "6", "b7"], formula: "1 2 b3 3 4 5 6 b7" },
    { name: "Bebop Mixolydian", notes: [0, 2, 4, 5, 7, 9, 10, 11], intervals: ["1", "2", "3", "4", "5", "6", "b7", "7"], formula: "1 2 3 4 5 6 b7 7" },
    { name: "Bebop Minor", notes: [0, 2, 3, 5, 7, 8, 9, 10], intervals: ["1", "2", "b3", "4", "5", "b6", "6", "b7"], formula: "1 2 b3 4 5 b6 6 b7" },
  ],
  jazz: [
    { name: "Lydian Dominant", notes: [0, 2, 4, 6, 7, 9, 10], intervals: ["1", "2", "3", "#4", "5", "6", "b7"], formula: "1 2 3 #4 5 6 b7" },
    { name: "Altered", notes: [0, 1, 3, 4, 6, 8, 10], intervals: ["1", "b2", "b3", "3", "b5", "b6", "b7"], formula: "1 b2 b3 3 b5 b6 b7" },
    { name: "Half-Whole Diminished", notes: [0, 1, 3, 4, 6, 7, 9, 10], intervals: ["1", "b2", "b3", "3", "#4", "5", "6", "b7"], formula: "1 b2 b3 3 #4 5 6 b7" },
    { name: "Whole-Half Diminished", notes: [0, 2, 3, 5, 6, 8, 9, 11], intervals: ["1", "2", "b3", "4", "b5", "b6", "6", "7"], formula: "1 2 b3 4 b5 b6 6 7" },
    { name: "Harmonic Major", notes: [0, 2, 4, 5, 7, 8, 11], intervals: ["1", "2", "3", "4", "5", "b6", "7"], formula: "1 2 3 4 5 b6 7" },
    { name: "Hungarian Minor", notes: [0, 2, 3, 6, 7, 8, 11], intervals: ["1", "2", "b3", "#4", "5", "b6", "7"], formula: "1 2 b3 #4 5 b6 7" },
  ],
}

export const SCALE_PRACTICE_SEQUENCES = [
  { id: "1to1", name: "1→1", nameKey: "scale_seq_1to1", description: "从根音到根音" },
  { id: "3to3", name: "3→3", nameKey: "scale_seq_3to3", description: "从三音到三音" },
  { id: "5to5", name: "5→5", nameKey: "scale_seq_5to5", description: "从五音到五音" },
  { id: "7to7", name: "7→7", nameKey: "scale_seq_7to7", description: "从七音到七音" },
  { id: "random", name: "随机", nameKey: "random", description: "随机琶音" },
  // 一弦三音（3NPS）：不是「首尾音级」而是一套**把位指型**，见 lib/three-notes-per-string.ts。
  // 它借用本列表只是为了复用「音阶序列」这个单选控件，语义上另起一类。
  { id: "3nps", name: "一弦3音", nameKey: "scale_seq_3nps", description: "每弦三个音的七个把位" },
]


export const DISPLAY_NAMES = {
  "chinese": {
    "chordTypes": {
      "6": "大六和弦",
      "7": "属七和弦",
      "9": "属九和弦",
      "11": "属十一和弦",
      "13": "属十三和弦",
      "Major": "大三和弦",
      "Minor": "小三和弦",
      "Dim": "减三和弦",
      "Aug": "增三和弦",
      "m6": "小六和弦",
      "Maj7": "大七和弦",
      "m7": "小七和弦",
      "m7b5": "半减七和弦",
      "dim7": "减七和弦",
      "mMaj7": "小大七和弦",
      "aug7": "增七和弦",
      "7b5": "属七降五和弦",
      "7#5": "属七升五和弦",
      "maj7#5": "大七升五和弦",
      "Maj9": "大九和弦",
      "m9": "小九和弦",
      "m9b5": "小九降五和弦",
      "7#9": "属七升九和弦",
      "7b9": "属七降九和弦",
      "7#5b9": "属七升五降九和弦",
      "7#5#9": "属七升五升九和弦",
      "m11": "小十一和弦",
      "7#11": "属七升十一和弦",
      "9#11": "属九升十一和弦",
      "m13": "小十三和弦",
      "13b9": "属十三降九和弦",
      "13#11": "属十三升十一和弦",
      "sus2": "挂二和弦",
      "sus4": "挂四和弦",
      "7sus4": "属七挂四和弦",
      "9sus4": "属九挂四和弦",
      "add9": "加九和弦",
      "madd9": "小加九和弦",
      "6add9": "大六加九和弦",
      "m6add9": "小六加九和弦",

      // ── 补齐：原四段各只有 40 个键，共同缺这 25 个 ──
      // 缺的后果：中文界面会原样显示类型记谱（`7alt` / `maj13`）。
      // 四段键集合必须完全一致（getDisplayName 用联合类型索引，见 __tests__/chord-type-registry.test.ts），
      // 故 25 条在四段同步补齐；英文/爵士写法沿用各自既有约定（变化音用括号、jazz 小调用 min）。
      "dimMaj7": "减大七和弦",
      "m7b5nat9": "半减七自然九和弦",
      "m7b6": "小七降六和弦",
      "mMaj9": "小大九和弦",
      "mMaj13": "小大十三和弦",
      "7b13": "属七降十三和弦",
      "7b5b9": "属七降五降九和弦",
      "7b5#9": "属七降五升九和弦",
      "7b9b13": "属七降九降十三和弦",
      "7alt": "变化属七和弦",
      "9b13": "属九降十三和弦",
      "13#9": "属十三升九和弦",
      "7sus4b9": "属七挂四降九和弦",
      "sus4b9": "挂四降九和弦",
      "13sus4": "属十三挂四和弦",
      "13sus4b9": "属十三挂四降九和弦",
      "maj7#11": "大七升十一和弦",
      "maj7b6": "大七降六和弦",
      "maj7#9": "大七升九和弦",
      "maj9#11": "大九升十一和弦",
      "maj9#5": "大九升五和弦",
      "maj9b6": "大九降六和弦",
      "maj13": "大十三和弦",
      "maj13#11": "大十三升十一和弦",
      "maj13#5": "大十三升五和弦",
    },
    "scaleTypes": {
      "Major": "大调音阶",
      "Minor": "小调音阶",
      "Ionian": "伊奥尼亚调式",
      "Dorian": "多利亚调式",
      "Phrygian": "弗里几亚调式",
      "Lydian": "利底亚调式",
      "Mixolydian": "混合利底亚调式",
      "Aeolian": "爱奥利亚调式",
      "Locrian": "洛克里亚调式",
      "Harmonic Minor": "和声小调",
      "Melodic Minor": "旋律小调",
      "Major Pentatonic": "大调五声音阶",
      "Minor Pentatonic": "小调五声音阶",
      "Dominant Pentatonic": "属七五声音阶",
      "Minor 6 Pentatonic": "小六五声音阶",
      "Blues": "布鲁斯音阶",
      "Major Blues": "大调布鲁斯",
      "Whole Tone": "全音音阶",
      "Lydian Dominant": "利底亚属音阶",
      "Altered": "变化音阶",
      "Half-Whole Diminished": "半全减音阶",
      "Whole-Half Diminished": "全半减音阶",
      "Diminished Half Whole": "减音阶半全",
      "Diminished Whole Half": "减音阶全半",
      "Harmonic Major": "和声大调",
      "Hungarian Minor": "匈牙利小调",
      "Japanese": "日本音阶",
      "Egyptian": "埃及音阶",
      "Spanish Phrygian": "西班牙弗里几亚",
      "Hijaz": "希贾兹音阶",
      "Double Harmonic": "双和声音阶",
      "Chromatic": "半音阶",
      "Augmented": "增音阶",
      "Augmented Scale": "增音阶",
      "Tritone": "三全音音阶",
      "Dorian b2": "多利亚b2",
      "Lydian Augmented": "利底亚增",
      "Mixolydian b6": "混合利底亚b6",
      "Locrian Nat 2": "洛克里亚自然2",
      "Locrian Nat 6": "洛克里亚自然6",
      "Ionian Augmented": "伊奥尼亚增",
      "Dorian #4": "多利亚#4",
      "Phrygian Dominant": "弗里几亚属",
      "Lydian #9": "利底亚#9",
      "Superlocrian bb7": "超洛克里亚bb7",
      "Dorian b5": "多利亚b5",
      "Phrygian b4": "弗里几亚b4",
      "Lydian b3": "利底亚b3",
      "Mixolydian b2": "混合利底亚b2",
      "Lydian Augmented #2": "利底亚增#2",
      "Locrian bb7": "洛克里亚bb7",
      "Bebop Dominant": "Bebop属音阶",
      "Bebop Major": "Bebop大调",
      "Bebop Dorian": "Bebop多利亚",
      "Bebop Tonic Minor": "Bebop主小调",
      "Bebop Dom7b9b13": "Bebop属7b9b13",
      "Bebop Tonic Minor Dorian": "Bebop主小调(多利亚)",
      "Bebop Tonic Minor Melodic": "Bebop主小调(旋律)",
      "Bebop Mixolydian": "Bebop混合利底亚",
      "Bebop Minor": "Bebop小调"
    }
  },
  "english": {
    "chordTypes": {
      "6": "6",
      "7": "7",
      "9": "9",
      "11": "11",
      "13": "13",
      "Major": "Major",
      "Minor": "Minor",
      "Dim": "Dim",
      "Aug": "Aug",
      "m6": "m6",
      "Maj7": "Maj7",
      "m7": "m7",
      "m7b5": "m7b5",
      "dim7": "dim7",
      "mMaj7": "m(maj7)",
      "aug7": "aug7",
      "7b5": "7(b5)",
      "7#5": "7(#5)",
      "maj7#5": "maj7(#5)",
      "Maj9": "Maj9",
      "m9": "m9",
      "m9b5": "m9(b5)",
      "7#9": "7(#9)",
      "7b9": "7(b9)",
      "7#5b9": "7(#5b9)",
      "7#5#9": "7(#5#9)",
      "m11": "m11",
      "7#11": "7(#11)",
      "9#11": "9(#11)",
      "m13": "m13",
      "13b9": "13(b9)",
      "13#11": "13(#11)",
      "sus2": "sus2",
      "sus4": "sus4",
      "7sus4": "7sus4",
      "9sus4": "9sus4",
      "add9": "add9",
      "madd9": "m(add9)",
      "6add9": "6/9",
      "m6add9": "m6/9",

      // ── 补齐：原四段各只有 40 个键，共同缺这 25 个 ──
      // 缺的后果：中文界面会原样显示类型记谱（`7alt` / `maj13`）。
      // 四段键集合必须完全一致（getDisplayName 用联合类型索引，见 __tests__/chord-type-registry.test.ts），
      // 故 25 条在四段同步补齐；英文/爵士写法沿用各自既有约定（变化音用括号、jazz 小调用 min）。
      "dimMaj7": "dim(maj7)",
      "m7b5nat9": "m7b5(nat9)",
      "m7b6": "m7(b6)",
      "mMaj9": "m(maj9)",
      "mMaj13": "m(maj13)",
      "7b13": "7(b13)",
      "7b5b9": "7(b5b9)",
      "7b5#9": "7(b5#9)",
      "7b9b13": "7(b9b13)",
      "7alt": "7alt",
      "9b13": "9(b13)",
      "13#9": "13(#9)",
      "7sus4b9": "7sus4(b9)",
      "sus4b9": "sus4(b9)",
      "13sus4": "13sus4",
      "13sus4b9": "13sus4(b9)",
      "maj7#11": "maj7(#11)",
      "maj7b6": "maj7(b6)",
      "maj7#9": "maj7(#9)",
      "maj9#11": "maj9(#11)",
      "maj9#5": "maj9(#5)",
      "maj9b6": "maj9(b6)",
      "maj13": "maj13",
      "maj13#11": "maj13(#11)",
      "maj13#5": "maj13(#5)",
    },
    "scaleTypes": {
      "Major": "Major Scale",
      "Minor": "Minor Scale",
      "Ionian": "Ionian Mode",
      "Dorian": "Dorian Mode",
      "Phrygian": "Phrygian Mode",
      "Lydian": "Lydian Mode",
      "Mixolydian": "Mixolydian Mode",
      "Aeolian": "Aeolian Mode",
      "Locrian": "Locrian Mode",
      "Harmonic Minor": "Harmonic Minor",
      "Melodic Minor": "Melodic Minor",
      "Major Pentatonic": "Major Pentatonic",
      "Minor Pentatonic": "Minor Pentatonic",
      "Dominant Pentatonic": "Dominant Pentatonic",
      "Minor 6 Pentatonic": "Minor 6 Pentatonic",
      "Blues": "Blues Scale",
      "Major Blues": "Major Blues",
      "Whole Tone": "Whole Tone",
      "Lydian Dominant": "Lydian Dominant",
      "Altered": "Altered Scale",
      "Half-Whole Diminished": "Half-Whole Dim",
      "Whole-Half Diminished": "Whole-Half Dim",
      "Diminished Half Whole": "Diminished H-W",
      "Diminished Whole Half": "Diminished W-H",
      "Harmonic Major": "Harmonic Major",
      "Hungarian Minor": "Hungarian Minor",
      "Japanese": "Japanese Scale",
      "Egyptian": "Egyptian Scale",
      "Spanish Phrygian": "Spanish Phrygian",
      "Hijaz": "Hijaz Scale",
      "Double Harmonic": "Double Harmonic",
      "Chromatic": "Chromatic Scale",
      "Augmented": "Augmented Scale",
      "Augmented Scale": "Augmented Scale",
      "Tritone": "Tritone Scale",
      "Dorian b2": "Dorian b2",
      "Lydian Augmented": "Lydian Augmented",
      "Mixolydian b6": "Mixolydian b6",
      "Locrian Nat 2": "Locrian Nat 2",
      "Locrian Nat 6": "Locrian Nat 6",
      "Ionian Augmented": "Ionian Augmented",
      "Dorian #4": "Dorian #4",
      "Phrygian Dominant": "Phrygian Dominant",
      "Lydian #9": "Lydian #9",
      "Superlocrian bb7": "Superlocrian bb7",
      "Dorian b5": "Dorian b5",
      "Phrygian b4": "Phrygian b4",
      "Lydian b3": "Lydian b3",
      "Mixolydian b2": "Mixolydian b2",
      "Lydian Augmented #2": "Lydian Aug #2",
      "Locrian bb7": "Locrian bb7",
      "Bebop Dominant": "Bebop Dominant",
      "Bebop Major": "Bebop Major",
      "Bebop Dorian": "Bebop Dorian",
      "Bebop Tonic Minor": "Bebop Tonic Minor",
      "Bebop Dom7b9b13": "Bebop Dom7b9b13",
      "Bebop Tonic Minor Dorian": "Bebop Tonic Minor (Dorian)"
    }
  },
  "english_short": {
    "chordTypes": {
      "6": "6",
      "7": "7",
      "9": "9",
      "11": "11",
      "13": "13",
      "Major": "",
      "Minor": "m",
      "Dim": "dim",
      "Aug": "aug",
      "m6": "m6",
      "Maj7": "Maj7",
      "m7": "m7",
      "m7b5": "m7b5",
      "dim7": "dim7",
      "mMaj7": "m(maj7)",
      "aug7": "aug7",
      "7b5": "7(b5)",
      "7#5": "7(#5)",
      "maj7#5": "maj7(#5)",
      "Maj9": "Maj9",
      "m9": "m9",
      "m9b5": "m9(b5)",
      "7#9": "7(#9)",
      "7b9": "7(b9)",
      "7#5b9": "7(#5b9)",
      "7#5#9": "7(#5#9)",
      "m11": "m11",
      "7#11": "7(#11)",
      "9#11": "9(#11)",
      "m13": "m13",
      "13b9": "13(b9)",
      "13#11": "13(#11)",
      "sus2": "sus2",
      "sus4": "sus4",
      "7sus4": "7sus4",
      "9sus4": "9sus4",
      "add9": "add9",
      "madd9": "m(add9)",
      "6add9": "6/9",
      "m6add9": "m6/9",

      // ── 补齐：原四段各只有 40 个键，共同缺这 25 个 ──
      // 缺的后果：中文界面会原样显示类型记谱（`7alt` / `maj13`）。
      // 四段键集合必须完全一致（getDisplayName 用联合类型索引，见 __tests__/chord-type-registry.test.ts），
      // 故 25 条在四段同步补齐；英文/爵士写法沿用各自既有约定（变化音用括号、jazz 小调用 min）。
      "dimMaj7": "dim(maj7)",
      "m7b5nat9": "m7b5(nat9)",
      "m7b6": "m7(b6)",
      "mMaj9": "m(maj9)",
      "mMaj13": "m(maj13)",
      "7b13": "7(b13)",
      "7b5b9": "7(b5b9)",
      "7b5#9": "7(b5#9)",
      "7b9b13": "7(b9b13)",
      "7alt": "7alt",
      "9b13": "9(b13)",
      "13#9": "13(#9)",
      "7sus4b9": "7sus4(b9)",
      "sus4b9": "sus4(b9)",
      "13sus4": "13sus4",
      "13sus4b9": "13sus4(b9)",
      "maj7#11": "maj7(#11)",
      "maj7b6": "maj7(b6)",
      "maj7#9": "maj7(#9)",
      "maj9#11": "maj9(#11)",
      "maj9#5": "maj9(#5)",
      "maj9b6": "maj9(b6)",
      "maj13": "maj13",
      "maj13#11": "maj13(#11)",
      "maj13#5": "maj13(#5)",
    },
    "scaleTypes": {
      "Major": "Major",
      "Minor": "Minor",
      "Ionian": "Ionian",
      "Dorian": "Dorian",
      "Phrygian": "Phrygian",
      "Lydian": "Lydian",
      "Mixolydian": "Mixolydian",
      "Aeolian": "Aeolian",
      "Locrian": "Locrian",
      "Harmonic Minor": "Harm. Minor",
      "Melodic Minor": "Mel. Minor",
      "Major Pentatonic": "Maj Pent",
      "Minor Pentatonic": "Min Pent",
      "Dominant Pentatonic": "Dom Pent",
      "Minor 6 Pentatonic": "Min6 Pent",
      "Blues": "Blues",
      "Major Blues": "Maj Blues",
      "Whole Tone": "Whole Tone",
      "Lydian Dominant": "Lydian Dom",
      "Altered": "Altered",
      "Half-Whole Diminished": "H-W Dim",
      "Whole-Half Diminished": "W-H Dim",
      "Diminished Half Whole": "Dim H-W",
      "Diminished Whole Half": "Dim W-H",
      "Harmonic Major": "Harm. Major",
      "Hungarian Minor": "Hung. Minor",
      "Japanese": "Japanese",
      "Egyptian": "Egyptian",
      "Spanish Phrygian": "Spanish Phryg",
      "Hijaz": "Hijaz",
      "Double Harmonic": "Dbl Harm",
      "Chromatic": "Chromatic",
      "Augmented": "Augmented",
      "Augmented Scale": "Augmented",
      "Tritone": "Tritone",
      "Dorian b2": "Dorian b2",
      "Lydian Augmented": "Lydian Aug",
      "Mixolydian b6": "Mix b6",
      "Locrian Nat 2": "Locrian #2",
      "Locrian Nat 6": "Locrian #6",
      "Ionian Augmented": "Ionian Aug",
      "Dorian #4": "Dorian #4",
      "Phrygian Dominant": "Phryg Dom",
      "Lydian #9": "Lydian #9",
      "Superlocrian bb7": "Superloc bb7",
      "Dorian b5": "Dorian b5",
      "Phrygian b4": "Phryg b4",
      "Lydian b3": "Lydian b3",
      "Mixolydian b2": "Mix b2",
      "Lydian Augmented #2": "Lyd Aug #2",
      "Locrian bb7": "Locrian bb7",
      "Bebop Dominant": "Bebop Dom",
      "Bebop Major": "Bebop Maj",
      "Bebop Dorian": "Bebop Dor",
      "Bebop Tonic Minor": "Bebop Ton Min",
      "Bebop Dom7b9b13": "Bebop Dom7b9b13",
      "Bebop Tonic Minor Dorian": "Bebop Ton Min (Dor)"
    }
  },
  "jazz": {
    "chordTypes": {
      "6": "6",
      "7": "7",
      "9": "9",
      "11": "11",
      "13": "13",
      "Major": "Maj",
      "Minor": "min",
      "Dim": "dim",
      "Aug": "aug",
      "m6": "min6",
      "Maj7": "Maj7",
      "m7": "min7",
      "m7b5": "m7b5",
      "dim7": "dim7",
      "mMaj7": "min(maj7)",
      "aug7": "aug7",
      "7b5": "7(b5)",
      "7#5": "7(#5)",
      "maj7#5": "Maj7(#5)",
      "Maj9": "Maj9",
      "m9": "min9",
      "m9b5": "m9(b5)",
      "7#9": "7(#9)",
      "7b9": "7(b9)",
      "7#5b9": "7(#5b9)",
      "7#5#9": "7(#5#9)",
      "m11": "min11",
      "7#11": "7(#11)",
      "9#11": "9(#11)",
      "m13": "min13",
      "13b9": "13(b9)",
      "13#11": "13(#11)",
      "sus2": "sus2",
      "sus4": "sus4",
      "7sus4": "7sus4",
      "9sus4": "9sus4",
      "add9": "add9",
      "madd9": "min(add9)",
      "6add9": "6/9",
      "m6add9": "min6/9",

      // ── 补齐：原四段各只有 40 个键，共同缺这 25 个 ──
      // 缺的后果：中文界面会原样显示类型记谱（`7alt` / `maj13`）。
      // 四段键集合必须完全一致（getDisplayName 用联合类型索引，见 __tests__/chord-type-registry.test.ts），
      // 故 25 条在四段同步补齐；英文/爵士写法沿用各自既有约定（变化音用括号、jazz 小调用 min）。
      "dimMaj7": "dim(maj7)",
      "m7b5nat9": "m7b5(nat9)",
      "m7b6": "min7(b6)",
      "mMaj9": "min(maj9)",
      "mMaj13": "min(maj13)",
      "7b13": "7(b13)",
      "7b5b9": "7(b5b9)",
      "7b5#9": "7(b5#9)",
      "7b9b13": "7(b9b13)",
      "7alt": "7alt",
      "9b13": "9(b13)",
      "13#9": "13(#9)",
      "7sus4b9": "7sus4(b9)",
      "sus4b9": "sus4(b9)",
      "13sus4": "13sus4",
      "13sus4b9": "13sus4(b9)",
      "maj7#11": "Maj7(#11)",
      "maj7b6": "Maj7(b6)",
      "maj7#9": "Maj7(#9)",
      "maj9#11": "Maj9(#11)",
      "maj9#5": "Maj9(#5)",
      "maj9b6": "Maj9(b6)",
      "maj13": "Maj13",
      "maj13#11": "Maj13(#11)",
      "maj13#5": "Maj13(#5)",
    },
    "scaleTypes": {
      "Major": "Ionian",
      "Minor": "Aeolian",
      "Ionian": "Ionian",
      "Dorian": "Dorian",
      "Phrygian": "Phrygian",
      "Lydian": "Lydian",
      "Mixolydian": "Mixolydian",
      "Aeolian": "Aeolian",
      "Locrian": "Locrian",
      "Harmonic Minor": "Harm. Minor",
      "Melodic Minor": "Mel. Minor",
      "Major Pentatonic": "Maj Pent",
      "Minor Pentatonic": "min Pent",
      "Dominant Pentatonic": "Dom Pent",
      "Minor 6 Pentatonic": "min6 Pent",
      "Blues": "Blues",
      "Major Blues": "Maj Blues",
      "Whole Tone": "Whole Tone",
      "Lydian Dominant": "Lydian Dom",
      "Altered": "Altered",
      "Half-Whole Diminished": "H-W Dim",
      "Whole-Half Diminished": "W-H Dim",
      "Diminished Half Whole": "Dim H-W",
      "Diminished Whole Half": "Dim W-H",
      "Harmonic Major": "Harm. Major",
      "Hungarian Minor": "Hung. Minor",
      "Japanese": "Japanese",
      "Egyptian": "Egyptian",
      "Spanish Phrygian": "Spanish Phryg",
      "Hijaz": "Hijaz",
      "Double Harmonic": "Dbl Harm",
      "Chromatic": "Chromatic",
      "Augmented": "Augmented",
      "Augmented Scale": "Augmented",
      "Tritone": "Tritone",
      "Dorian b2": "Dorian b2",
      "Lydian Augmented": "Lydian Aug",
      "Mixolydian b6": "Mix b6",
      "Locrian Nat 2": "Locrian #2",
      "Locrian Nat 6": "Locrian #6",
      "Ionian Augmented": "Ionian Aug",
      "Dorian #4": "Dorian #4",
      "Phrygian Dominant": "Phryg Dom",
      "Lydian #9": "Lydian #9",
      "Superlocrian bb7": "Superloc bb7",
      "Dorian b5": "Dorian b5",
      "Phrygian b4": "Phryg b4",
      "Lydian b3": "Lydian b3",
      "Mixolydian b2": "Mix b2",
      "Lydian Augmented #2": "Lyd Aug #2",
      "Locrian bb7": "Locrian bb7",
      "Bebop Dominant": "Bebop Dom",
      "Bebop Major": "Bebop Maj",
      "Bebop Dorian": "Bebop Dor",
      "Bebop Tonic Minor": "Bebop Ton Min",
      "Bebop Dom7b9b13": "Bebop Dom7b9b13",
      "Bebop Tonic Minor Dorian": "Bebop Ton Min (Dor)"
    }
  }
}
