export interface PracticeLevel {
  id: string
  nameKey: string
  name: string
  nameZh: string
  description: string
  descriptionZh: string
  groupName: string
  groupNameZh: string
  sequences: {
    dominant: number[]
    major: number[]
    minor: number[]
    sus: number[]
    diminished: number[]
    diminishedDominant: number[]
    six: number[]
    altered?: number[]
    sus2?: number[]
    augmented?: number[]
    diminishedMajorSeven?: number[]
  }
  startingIntervalOption: "any" | "first" | "chordTone"
  takeStartingIntervalBeforeOrder: boolean
  orderOption: boolean
  randomOption: boolean
  forceNaturalFive: boolean
  notesPerChord: number
  endOnStartingInterval?: boolean
  usePassingNoteBebopScale?: boolean
}

export const SINGLE_CHORD_TONES_LEVELS: PracticeLevel[] = [
  {
    id: "single_chord_tones_root",
    nameKey: "level_root",
    name: "Root",
    nameZh: "根音",
    description: "Single chord tones\n\nRoot notes only",
    descriptionZh: "单和弦音\n\n仅练习根音",
    groupName: "Single Chord Tones",
    groupNameZh: "单和弦音",
    sequences: {
      dominant: [1],
      major: [1],
      minor: [1],
      sus: [1],
      diminished: [1],
      diminishedDominant: [1],
      six: [1],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 1,
  },
  {
    id: "single_chord_tones_3rd",
    nameKey: "level_3rd",
    name: "3rd",
    nameZh: "三音",
    description: "Single chord tones\n\n3rd only\n2nd or 4th on sus chords",
    descriptionZh: "单和弦音\n\n仅练习三音\n挂留和弦使用二音或四音",
    groupName: "Single Chord Tones",
    groupNameZh: "单和弦音",
    sequences: {
      dominant: [3],
      major: [3],
      minor: [3],
      sus: [4],
      diminished: [3],
      diminishedDominant: [4],
      six: [3],
      sus2: [2],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 1,
  },
  {
    id: "single_chord_tones_5th",
    nameKey: "level_5th",
    name: "5th",
    nameZh: "五音",
    description: "Single chord tones\n\n5th only\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "单和弦音\n\n仅练习五音\n\n（属和弦不使用变化五音）",
    groupName: "Single Chord Tones",
    groupNameZh: "单和弦音",
    sequences: {
      dominant: [5],
      major: [5],
      minor: [5],
      sus: [5],
      diminished: [5],
      diminishedDominant: [6],
      six: [5],
      augmented: [6],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 1,
  },
  {
    id: "single_chord_tones_7th",
    nameKey: "level_7th",
    name: "7th",
    nameZh: "七音",
    description: "Single chord tones\n\n7th only\n\n(6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "单和弦音\n\n仅练习七音\n\n（六和弦和减和弦使用六音/♭♭7）",
    groupName: "Single Chord Tones",
    groupNameZh: "单和弦音",
    sequences: {
      dominant: [7],
      major: [7],
      minor: [7],
      sus: [7],
      diminished: [7],
      diminishedDominant: [8],
      six: [6],
      diminishedMajorSeven: [8],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 1,
  },
]

export const TWO_CHORD_TONES_LEVELS: PracticeLevel[] = [
  {
    id: "two_chord_tones_root_3rd",
    nameKey: "level_root_3rd",
    name: "Root, 3rd",
    nameZh: "根音、三音",
    description: "Two chord tones\n\nRoot & 3rd\n\n(2nd or 4th on sus chords)",
    descriptionZh: "双和弦音\n\n根音和三音\n\n（挂留和弦使用二音或四音）",
    groupName: "Two Chord Tones",
    groupNameZh: "双和弦音",
    sequences: {
      dominant: [1, 3],
      major: [1, 3],
      minor: [1, 3],
      sus: [1, 4],
      diminished: [1, 3],
      diminishedDominant: [1, 4],
      six: [1, 3],
      sus2: [1, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 2,
  },
  {
    id: "two_chord_tones_root_5th",
    nameKey: "level_root_5th",
    name: "Root, 5th",
    nameZh: "根音、五音",
    description: "Two chord tones\n\nRoot & 5th\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "双和弦音\n\n根音和五音\n\n（属和弦不使用变化五音）",
    groupName: "Two Chord Tones",
    groupNameZh: "双和弦音",
    sequences: {
      dominant: [1, 5],
      major: [1, 5],
      minor: [1, 5],
      sus: [1, 5],
      diminished: [1, 5],
      diminishedDominant: [1, 6],
      six: [1, 5],
      augmented: [1, 6],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 2,
  },
  {
    id: "two_chord_tones_root_7th",
    nameKey: "level_root_7th",
    name: "Root, 7th",
    nameZh: "根音、七音",
    description: "Two chord tones\n\nRoot & 7th\n\n(6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "双和弦音\n\n根音和七音\n\n（六和弦和减和弦使用六音/♭♭7）",
    groupName: "Two Chord Tones",
    groupNameZh: "双和弦音",
    sequences: {
      dominant: [1, 7],
      major: [1, 7],
      minor: [1, 7],
      sus: [1, 7],
      diminished: [1, 7],
      diminishedDominant: [1, 8],
      six: [1, 6],
      diminishedMajorSeven: [1, 8],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 2,
  },
  {
    id: "two_chord_tones_3rd_5th",
    nameKey: "level_3rd_5th",
    name: "3rd, 5th",
    nameZh: "三音、五音",
    description: "Two chord tones\n\n3rd & 5th\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords)",
    descriptionZh: "双和弦音\n\n三音和五音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音）",
    groupName: "Two Chord Tones",
    groupNameZh: "双和弦音",
    sequences: {
      dominant: [3, 5],
      major: [3, 5],
      minor: [3, 5],
      sus: [4, 5],
      diminished: [3, 5],
      diminishedDominant: [4, 6],
      six: [3, 5],
      augmented: [4, 6],
      sus2: [2, 5],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 2,
  },
  {
    id: "two_chord_tones_3rd_7th",
    nameKey: "level_3rd_7th",
    name: "3rd, 7th",
    nameZh: "三音、七音",
    description: "Two chord tones\n\n3rd & 7th\n\n(2nd or 4th on sus chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "双和弦音\n\n三音和七音\n\n（挂留和弦使用二音或四音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Two Chord Tones",
    groupNameZh: "双和弦音",
    sequences: {
      dominant: [3, 7],
      major: [3, 7],
      minor: [3, 7],
      sus: [4, 7],
      diminished: [3, 7],
      diminishedDominant: [4, 8],
      six: [3, 6],
      diminishedMajorSeven: [3, 8],
      sus2: [2, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 2,
  },
  {
    id: "two_chord_tones_5th_7th",
    nameKey: "level_5th_7th",
    name: "5th, 7th",
    nameZh: "五音、七音",
    description: "Two chord tones\n\n5th & 7th\n\n(No altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "双和弦音\n\n五音和七音\n\n（属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Two Chord Tones",
    groupNameZh: "双和弦音",
    sequences: {
      dominant: [5, 7],
      major: [5, 7],
      minor: [5, 7],
      sus: [5, 7],
      diminished: [5, 7],
      diminishedDominant: [6, 8],
      six: [5, 6],
      augmented: [6, 7],
      diminishedMajorSeven: [5, 8],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 2,
  },
]

export const THREE_CHORD_TONES_LEVELS: PracticeLevel[] = [
  {
    id: "three_chord_tones_root_3rd_5th",
    nameKey: "level_root_3rd_5th",
    name: "Root, 3rd, 5th",
    nameZh: "根音、三音、五音",
    description: "Three chord tones\n\nRoot, 3rd & 5th\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords)",
    descriptionZh: "三和弦音\n\n根音、三音和五音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音）",
    groupName: "Three Chord Tones",
    groupNameZh: "三和弦音",
    sequences: {
      dominant: [1, 3, 5],
      major: [1, 3, 5],
      minor: [1, 3, 5],
      sus: [1, 4, 5],
      diminished: [1, 3, 5],
      diminishedDominant: [1, 4, 6],
      six: [1, 3, 5],
      augmented: [1, 4, 6],
      sus2: [1, 2, 5],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 3,
  },
  {
    id: "three_chord_tones_root_3rd_7th",
    nameKey: "level_root_3rd_7th",
    name: "Root, 3rd, 7th",
    nameZh: "根音、三音、七音",
    description: "Three chord tones\n\nRoot, 3rd & 7th\n\n(2nd or 4th on sus chords)",
    descriptionZh: "三和弦音\n\n根音、三音和七音\n\n（挂留和弦使用二音或四音）",
    groupName: "Three Chord Tones",
    groupNameZh: "三和弦音",
    sequences: {
      dominant: [1, 3, 7],
      major: [1, 3, 7],
      minor: [1, 3, 7],
      sus: [1, 4, 7],
      diminished: [1, 3, 7],
      diminishedDominant: [1, 4, 8],
      six: [1, 3, 7],
      diminishedMajorSeven: [1, 3, 8],
      sus2: [1, 2, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 3,
  },
  {
    id: "three_chord_tones_3rd_5th_7th",
    nameKey: "level_3rd_5th_7th",
    name: "3rd, 5th, 7th",
    nameZh: "三音、五音、七音",
    description: "Three chord tones\n\n3rd, 5th & 7th\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "三和弦音\n\n三音、五音和七音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Three Chord Tones",
    groupNameZh: "三和弦音",
    sequences: {
      dominant: [3, 5, 7],
      major: [3, 5, 7],
      minor: [3, 5, 7],
      sus: [4, 5, 7],
      diminished: [3, 5, 7],
      diminishedDominant: [4, 6, 8],
      six: [3, 5, 6],
      augmented: [4, 6, 7],
      diminishedMajorSeven: [3, 5, 8],
      sus2: [2, 5, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 3,
  },
  {
    id: "three_chord_tones_random_inversions",
    nameKey: "level_random_inversions",
    name: "Root, 3rd, 5th (Random Inversions)",
    nameZh: "根音、三音、五音（随机转位）",
    description: "Three chord tones\n\nThis level randomises between:-\nRoot, 3rd & 5th\n3rd, 5th, Root\n5th, Root, 3rd\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords)",
    descriptionZh: "三和弦音\n\n此模式在以下排列中随机选择：\n根音、三音、五音\n三音、五音、根音\n五音、根音、三音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音）",
    groupName: "Three Chord Tones",
    groupNameZh: "三和弦音",
    sequences: {
      dominant: [1, 3, 5],
      major: [1, 3, 5],
      minor: [1, 3, 5],
      sus: [1, 4, 5],
      diminished: [1, 3, 5],
      diminishedDominant: [1, 4, 6],
      six: [1, 3, 5],
      augmented: [1, 4, 6],
      sus2: [1, 2, 5],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 3,
  },
]

export const FOUR_CHORD_TONES_LEVELS: PracticeLevel[] = [
  {
    id: "four_chord_tones_root_3rd_5th_7th",
    nameKey: "level_root_3rd_5th_7th",
    name: "Root, 3rd, 5th, 7th",
    nameZh: "根音、三音、五音、七音",
    description: "Four chord tones\n\nRoot, 3rd, 5th & 7th\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n根音、三音、五音和七音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [1, 3, 5, 7],
      major: [1, 3, 5, 7],
      minor: [1, 3, 5, 7],
      sus: [1, 4, 5, 7],
      diminished: [1, 3, 5, 7],
      diminishedDominant: [1, 4, 6, 8],
      six: [1, 3, 5, 6],
      augmented: [1, 4, 6, 7],
      diminishedMajorSeven: [1, 3, 5, 8],
      sus2: [1, 2, 5, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "four_chord_tones_3rd_5th_7th_root",
    nameKey: "level_3rd_5th_7th_root",
    name: "3rd, 5th, 7th, Root",
    nameZh: "三音、五音、七音、根音",
    description: "Four chord tones\n\n3rd, 5th, 7th, Root\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n三音、五音、七音、根音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [3, 5, 7, 1],
      major: [3, 5, 7, 1],
      minor: [3, 5, 7, 1],
      sus: [4, 5, 7, 1],
      diminished: [3, 5, 7, 1],
      diminishedDominant: [4, 6, 8, 1],
      six: [3, 5, 6, 1],
      augmented: [4, 6, 7, 1],
      diminishedMajorSeven: [3, 5, 8, 1],
      sus2: [2, 5, 7, 1],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "four_chord_tones_5th_7th_root_3rd",
    nameKey: "level_5th_7th_root_3rd",
    name: "5th, 7th, Root, 3rd",
    nameZh: "五音、七音、根音、三音",
    description: "Four chord tones\n\n5th, 7th, Root, 3rd\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n五音、七音、根音、三音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [5, 7, 1, 3],
      major: [5, 7, 1, 3],
      minor: [5, 7, 1, 3],
      sus: [5, 7, 1, 4],
      diminished: [5, 7, 1, 3],
      diminishedDominant: [6, 8, 1, 4],
      six: [5, 6, 1, 3],
      augmented: [6, 7, 1, 4],
      diminishedMajorSeven: [5, 8, 1, 3],
      sus2: [5, 7, 1, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "four_chord_tones_7th_root_3rd_5th",
    nameKey: "level_7th_root_3rd_5th",
    name: "7th, Root, 3rd, 5th",
    nameZh: "七音、根音、三音、五音",
    description: "Four chord tones\n\n7th, Root, 3rd, 5th\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n七音、根音、三音、五音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [7, 1, 3, 5],
      major: [7, 1, 3, 5],
      minor: [7, 1, 3, 5],
      sus: [7, 1, 4, 5],
      diminished: [7, 1, 3, 5],
      diminishedDominant: [8, 1, 4, 6],
      six: [6, 1, 3, 5],
      augmented: [7, 1, 4, 6],
      diminishedMajorSeven: [8, 1, 3, 5],
      sus2: [7, 1, 2, 5],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "four_chord_tones_random_inversions",
    nameKey: "level_four_random_inversions",
    name: "Root, 3rd, 5th, 7th (Random Inversions)",
    nameZh: "根音、三音、五音、七音（随机转位）",
    description: "Four chord tones\n\nThis level randomises between:-\nRoot, 3rd, 5th & 7th\n3rd, 5th, 7th, Root\n5th, 7th, Root, 3rd\n7th, Root, 3rd, 5th\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n此模式在以下排列中随机选择：\n根音、三音、五音、七音\n三音、五音、七音、根音\n五音、七音、根音、三音\n七音、根音、三音、五音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [1, 3, 5, 7],
      major: [1, 3, 5, 7],
      minor: [1, 3, 5, 7],
      sus: [1, 4, 5, 7],
      diminished: [1, 3, 5, 7],
      diminishedDominant: [1, 4, 6, 8],
      six: [1, 3, 5, 6],
      augmented: [1, 4, 6, 7],
      diminishedMajorSeven: [1, 3, 5, 8],
      sus2: [1, 2, 5, 7],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "four_chord_tones_random_order",
    nameKey: "level_four_random_order",
    name: "Root, 3rd, 5th, 7th (Random Order)",
    nameZh: "根音、三音、五音、七音（随机顺序）",
    description: "Four chord tones\n\nRoot, 3rd, 5th & 7th in random order\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n根音、三音、五音和七音随机顺序\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [1, 3, 5, 7],
      major: [1, 3, 5, 7],
      minor: [1, 3, 5, 7],
      sus: [1, 4, 5, 7],
      diminished: [1, 3, 5, 7],
      diminishedDominant: [1, 4, 6, 8],
      six: [1, 3, 5, 6],
      augmented: [1, 4, 6, 7],
      diminishedMajorSeven: [1, 3, 5, 8],
      sus2: [1, 2, 5, 7],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "four_chord_tones_root_3rd_5th_7th_root",
    nameKey: "level_root_3rd_5th_7th_root",
    name: "Root, 3rd, 5th, 7th, Root",
    nameZh: "根音、三音、五音、七音、根音",
    description: "Four chord tones\n\nRoot, 3rd, 5th, 7th & Root\n\n(2nd or 4th on sus chords\nNo altered 5ths on dominant chords\n6th/♭♭7 on 6th & diminished chords)",
    descriptionZh: "四和弦音\n\n根音、三音、五音、七音、根音\n\n（挂留和弦使用二音或四音\n属和弦不使用变化五音\n六和弦和减和弦使用六音/♭♭7）",
    groupName: "Four Chord Tones",
    groupNameZh: "四和弦音",
    sequences: {
      dominant: [1, 3, 5, 7],
      major: [1, 3, 5, 7],
      minor: [1, 3, 5, 7],
      sus: [1, 4, 5, 7],
      diminished: [1, 3, 5, 7],
      diminishedDominant: [1, 4, 6, 8],
      six: [1, 3, 5, 6],
      augmented: [1, 4, 6, 7],
      diminishedMajorSeven: [1, 3, 5, 8],
      sus2: [1, 2, 5, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 5,
    endOnStartingInterval: true,
  },
]

export const MELODIC_ROOT_TO_5TH_LEVELS: PracticeLevel[] = [
  {
    id: "melodic_structure_1",
    nameKey: "level_melodic_structure_1",
    name: "Melodic Structure 1",
    nameZh: "旋律结构 1",
    description: "Melodic structures - Root to 5th\n\n1, 2, 3, 5 on major/dominant chords\n\n1, 3, 4, 5 on minor chords\n\n1, 2, 4, 5 on sus chords\n\n1, 2, 3, 5 on diminished chords\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "旋律结构 - 根音到五音\n\n大调/属和弦：1, 2, 3, 5\n\n小调和弦：1, 3, 4, 5\n\n挂留和弦：1, 2, 4, 5\n\n减和弦：1, 2, 3, 5\n\n（属和弦不使用变化五音）",
    groupName: "Melodic Structures - Root to 5th",
    groupNameZh: "旋律结构 - 根音到五音",
    sequences: {
      dominant: [1, 2, 3, 5],
      major: [1, 2, 3, 5],
      minor: [1, 3, 4, 5],
      sus: [1, 2, 4, 5],
      diminished: [1, 2, 3, 5],
      diminishedDominant: [1, 2, 4, 6],
      six: [1, 2, 3, 5],
      augmented: [1, 2, 4, 6],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_2",
    nameKey: "level_melodic_structure_2",
    name: "Melodic Structure 2",
    nameZh: "旋律结构 2",
    description: "Melodic structures - Root to 5th\n\n2, 1, 5, 3 on major/dominant chords\n\n3, 1, 5, 4 on minor chords\n\n2, 1, 5, 4 on sus chords\n\n2, 1, 5, 3 on diminished chords\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "旋律结构 - 根音到五音\n\n大调/属和弦：2, 1, 5, 3\n\n小调和弦：3, 1, 5, 4\n\n挂留和弦：2, 1, 5, 4\n\n减和弦：2, 1, 5, 3\n\n（属和弦不使用变化五音）",
    groupName: "Melodic Structures - Root to 5th",
    groupNameZh: "旋律结构 - 根音到五音",
    sequences: {
      dominant: [2, 1, 5, 3],
      major: [2, 1, 5, 3],
      minor: [3, 1, 5, 4],
      sus: [2, 1, 5, 4],
      diminished: [2, 1, 5, 3],
      diminishedDominant: [2, 1, 6, 4],
      six: [2, 1, 5, 3],
      augmented: [2, 1, 6, 4],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_3",
    nameKey: "level_melodic_structure_3",
    name: "Melodic Structure 3",
    nameZh: "旋律结构 3",
    description: "Melodic structures - Root to 5th\n\n3, 5, 2, 1 on major/dominant chords\n\n4, 5, 3, 1 on minor chords\n\n4, 5, 2, 1 on sus chords\n\n3, 5, 2, 1 on diminished chords\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "旋律结构 - 根音到五音\n\n大调/属和弦：3, 5, 2, 1\n\n小调和弦：4, 5, 3, 1\n\n挂留和弦：4, 5, 2, 1\n\n减和弦：3, 5, 2, 1\n\n（属和弦不使用变化五音）",
    groupName: "Melodic Structures - Root to 5th",
    groupNameZh: "旋律结构 - 根音到五音",
    sequences: {
      dominant: [3, 5, 2, 1],
      major: [3, 5, 2, 1],
      minor: [4, 5, 3, 1],
      sus: [4, 5, 2, 1],
      diminished: [3, 5, 2, 1],
      diminishedDominant: [4, 6, 2, 1],
      six: [3, 5, 2, 1],
      augmented: [4, 6, 2, 1],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_4",
    nameKey: "level_melodic_structure_4",
    name: "Melodic Structure 4",
    nameZh: "旋律结构 4",
    description: "Melodic structures - Root to 5th\n\n5, 1, 2, 3 on major/dominant chords\n\n5, 1, 3, 4 on minor chords\n\n5, 1, 2, 4 on sus chords\n\n5, 1, 2, 3 on diminished chords\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "旋律结构 - 根音到五音\n\n大调/属和弦：5, 1, 2, 3\n\n小调和弦：5, 1, 3, 4\n\n挂留和弦：5, 1, 2, 4\n\n减和弦：5, 1, 2, 3\n\n（属和弦不使用变化五音）",
    groupName: "Melodic Structures - Root to 5th",
    groupNameZh: "旋律结构 - 根音到五音",
    sequences: {
      dominant: [5, 1, 2, 3],
      major: [5, 1, 2, 3],
      minor: [5, 1, 3, 4],
      sus: [5, 1, 2, 4],
      diminished: [5, 1, 2, 3],
      diminishedDominant: [6, 1, 2, 4],
      six: [5, 1, 2, 3],
      augmented: [6, 1, 2, 4],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_5_random_inversions",
    nameKey: "level_melodic_structure_5",
    name: "Melodic Structure 5 (Random Inversions)",
    nameZh: "旋律结构 5（随机转位）",
    description: "Melodic structures - Root to 5th\n\nThis level creates random inversions of the following structures:-\n\n1, 2, 3, 5 on major/dominant chords\n\n1, 3, 4, 5 on minor chords\n\n1, 2, 4, 5 on sus chords\n\n1, 2, 3, 5 on diminished chords\n\n(No altered 5ths on dominant chords)",
    descriptionZh: "旋律结构 - 根音到五音\n\n此模式创建以下结构的随机转位：\n\n大调/属和弦：1, 2, 3, 5\n\n小调和弦：1, 3, 4, 5\n\n挂留和弦：1, 2, 4, 5\n\n减和弦：1, 2, 3, 5\n\n（属和弦不使用变化五音）",
    groupName: "Melodic Structures - Root to 5th",
    groupNameZh: "旋律结构 - 根音到五音",
    sequences: {
      dominant: [1, 2, 3, 5],
      major: [1, 2, 3, 5],
      minor: [1, 3, 4, 5],
      sus: [1, 2, 4, 5],
      diminished: [1, 2, 3, 5],
      diminishedDominant: [1, 2, 4, 6],
      six: [1, 2, 3, 5],
      augmented: [1, 2, 4, 6],
    },
    startingIntervalOption: "chordTone",
    takeStartingIntervalBeforeOrder: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
]

export const MELODIC_5TH_TO_9TH_LEVELS: PracticeLevel[] = [
  {
    id: "melodic_structure_6",
    nameKey: "level_melodic_structure_6",
    name: "Melodic Structure 6",
    nameZh: "旋律结构 6",
    description: "Melodic structures - 5th to 9th\n\n5, 6, 7, 2 on major/dominant chords\n\n5, 7, 1, 2 on minor chords\n\n5, 6, 7, 1 on diminished chords",
    descriptionZh: "旋律结构 - 五音到九音\n\n大调/属和弦：5, 6, 7, 2\n\n小调和弦：5, 7, 1, 2\n\n减和弦：5, 6, 7, 1",
    groupName: "Melodic Structures - 5th to 9th",
    groupNameZh: "旋律结构 - 五音到九音",
    sequences: {
      dominant: [5, 6, 7, 2],
      major: [5, 6, 7, 2],
      minor: [5, 7, 1, 2],
      sus: [5, 6, 7, 2],
      diminished: [5, 7, 8, 1],
      diminishedDominant: [6, 7, 8, 2],
      six: [5, 6, 7, 2],
      augmented: [6, 7, 1, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_7",
    nameKey: "level_melodic_structure_7",
    name: "Melodic Structure 7",
    nameZh: "旋律结构 7",
    description: "Melodic structures - 5th to 9th\n\n6, 5, 2, 7 on major/dominant chords\n\n7, 5, 2, 1 on minor chords\n\n6, 5, 1, 7 on diminished chords",
    descriptionZh: "旋律结构 - 五音到九音\n\n大调/属和弦：6, 5, 2, 7\n\n小调和弦：7, 5, 2, 1\n\n减和弦：6, 5, 1, 7",
    groupName: "Melodic Structures - 5th to 9th",
    groupNameZh: "旋律结构 - 五音到九音",
    sequences: {
      dominant: [6, 5, 2, 7],
      major: [6, 5, 2, 7],
      minor: [7, 5, 2, 1],
      sus: [6, 5, 2, 7],
      diminished: [7, 5, 1, 8],
      diminishedDominant: [7, 6, 2, 8],
      six: [6, 5, 2, 7],
      augmented: [7, 6, 2, 1],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_8",
    nameKey: "level_melodic_structure_8",
    name: "Melodic Structure 8",
    nameZh: "旋律结构 8",
    description: "Melodic structures - 5th to 9th\n\n7, 2, 6, 5 on major/dominant chords\n\n1, 2, 7, 5 on minor chords\n\n6, 1, 7, 5 on diminished chords",
    descriptionZh: "旋律结构 - 五音到九音\n\n大调/属和弦：7, 2, 6, 5\n\n小调和弦：1, 2, 7, 5\n\n减和弦：6, 1, 7, 5",
    groupName: "Melodic Structures - 5th to 9th",
    groupNameZh: "旋律结构 - 五音到九音",
    sequences: {
      dominant: [7, 2, 6, 5],
      major: [7, 2, 6, 5],
      minor: [1, 2, 7, 5],
      sus: [7, 2, 6, 5],
      diminished: [7, 1, 8, 5],
      diminishedDominant: [8, 2, 7, 6],
      six: [7, 2, 6, 5],
      augmented: [1, 2, 7, 6],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_9",
    nameKey: "level_melodic_structure_9",
    name: "Melodic Structure 9",
    nameZh: "旋律结构 9",
    description: "Melodic structures - 5th to 9th\n\n2, 7, 6, 5 on major/dominant chords\n\n2, 1, 7, 5 on minor chords\n\n2, 7, 1, 6 on diminished chords",
    descriptionZh: "旋律结构 - 五音到九音\n\n大调/属和弦：2, 7, 6, 5\n\n小调和弦：2, 1, 7, 5\n\n减和弦：2, 7, 1, 6",
    groupName: "Melodic Structures - 5th to 9th",
    groupNameZh: "旋律结构 - 五音到九音",
    sequences: {
      dominant: [2, 7, 6, 5],
      major: [2, 7, 6, 5],
      minor: [2, 1, 7, 5],
      sus: [2, 7, 6, 5],
      diminished: [2, 8, 1, 7],
      diminishedDominant: [2, 8, 7, 6],
      six: [2, 7, 6, 5],
      augmented: [2, 1, 7, 6],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "melodic_structure_10_random_inversions",
    nameKey: "level_melodic_structure_10",
    name: "Melodic Structure 10 (Random Inversions)",
    nameZh: "旋律结构 10（随机转位）",
    description: "Melodic structures - 5th to 9th\n\nThis level creates random inversions of the following structures:-\n\n5, 6, 7, 2 on major/dominant chords\n\n5, 7, 1, 2 on minor chords\n\n5, 6, 7, 1 on diminished chords",
    descriptionZh: "旋律结构 - 五音到九音\n\n此模式创建以下结构的随机转位：\n\n大调/属和弦：5, 6, 7, 2\n\n小调和弦：5, 7, 1, 2\n\n减和弦：5, 6, 7, 1",
    groupName: "Melodic Structures - 5th to 9th",
    groupNameZh: "旋律结构 - 五音到九音",
    sequences: {
      dominant: [5, 6, 7, 2],
      major: [5, 6, 7, 2],
      minor: [5, 7, 1, 2],
      sus: [5, 6, 7, 2],
      diminished: [5, 7, 8, 1],
      diminishedDominant: [6, 7, 8, 2],
      six: [5, 6, 7, 2],
      augmented: [6, 7, 1, 2],
    },
    startingIntervalOption: "chordTone",
    takeStartingIntervalBeforeOrder: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
]

export const VOICE_LED_LEVELS: PracticeLevel[] = [
  {
    id: "voice_led_structure_1",
    nameKey: "level_voice_led_1",
    name: "Voice Led Structure 1",
    nameZh: "Voice Led 结构 1",
    description: "Voice led structures\n\n3, 2, 1, 7 on minor chords\n\n3, 2, 1, 7 on dominant chords\n\n3, 2, 1, 7 on major chords\n\n4, 2, 1, 7 on sus chords\n\n3, 2, 1, 6 on diminished chords\n\n(Works best with cyclical progression e.g II-V-I)",
    descriptionZh: "Voice Led 声部连接\n\n小调和弦：3, 2, 1, 7\n\n属和弦：3, 2, 1, 7\n\n大调和弦：3, 2, 1, 7\n\n挂留和弦：4, 2, 1, 7\n\n减和弦：3, 2, 1, 6\n\n（最适合循环进行，如 II-V-I）",
    groupName: "Voice Led Structures",
    groupNameZh: "Voice Led 声部连接",
    sequences: {
      dominant: [3, 2, 1, 7],
      major: [3, 2, 1, 7],
      minor: [3, 2, 1, 7],
      sus: [4, 2, 1, 7],
      diminished: [3, 2, 1, 7],
      diminishedDominant: [4, 2, 1, 8],
      six: [3, 2, 1, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "voice_led_structure_2",
    nameKey: "level_voice_led_2",
    name: "Voice Led Structure 2",
    nameZh: "Voice Led 结构 2",
    description: "Voice led structures\n\n3, 2, 1, 7 on minor chords\n\n3, 5, 7, 2 on dominant chords\n\n5, 1, 2, 3 on major chords\n\n4, 5, 7, 2 on sus chords\n\n3, 2, 1, 6 on diminished chords\n\n(Works best with cyclical progression e.g II-V-I)",
    descriptionZh: "Voice Led 声部连接\n\n小调和弦：3, 2, 1, 7\n\n属和弦：3, 5, 7, 2\n\n大调和弦：5, 1, 2, 3\n\n挂留和弦：4, 5, 7, 2\n\n减和弦：3, 2, 1, 6\n\n（最适合循环进行，如 II-V-I）",
    groupName: "Voice Led Structures",
    groupNameZh: "Voice Led 声部连接",
    sequences: {
      dominant: [3, 5, 7, 2],
      major: [5, 1, 2, 3],
      minor: [3, 2, 1, 7],
      sus: [4, 5, 7, 2],
      diminished: [3, 2, 1, 7],
      diminishedDominant: [4, 6, 8, 2],
      six: [3, 5, 7, 2],
      augmented: [4, 6, 7, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "voice_led_structure_3",
    nameKey: "level_voice_led_3",
    name: "Voice Led Structure 3",
    nameZh: "Voice Led 结构 3",
    description: "Voice led structures\n\n1, 3, 5, 7 on minor chords\n\n3, 2, 1, 7 on dominant chords\n\n3, 2, 1, 7 on major chords\n\n4, 2, 1, 7 on sus chords\n\n3, 2, 1, 6 on diminished chords\n\n(Works best with cyclical progression e.g II-V-I)",
    descriptionZh: "Voice Led 声部连接\n\n小调和弦：1, 3, 5, 7\n\n属和弦：3, 2, 1, 7\n\n大调和弦：3, 2, 1, 7\n\n挂留和弦：4, 2, 1, 7\n\n减和弦：3, 2, 1, 6\n\n（最适合循环进行，如 II-V-I）",
    groupName: "Voice Led Structures",
    groupNameZh: "Voice Led 声部连接",
    sequences: {
      dominant: [3, 2, 1, 7],
      major: [3, 2, 1, 7],
      minor: [1, 3, 5, 7],
      sus: [4, 2, 1, 7],
      diminished: [3, 2, 1, 7],
      diminishedDominant: [4, 2, 1, 7],
      six: [3, 2, 1, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "voice_led_structure_4",
    nameKey: "level_voice_led_4",
    name: "Voice Led Structure 4",
    nameZh: "Voice Led 结构 4",
    description: "Voice led structures\n\n1, 3, 5, 7 on minor chords\n\n3, 5, 7, 2 on dominant chords\n\n3, 2, 1, 7 on major chords\n\n4, 5, 7, 2 on sus chords\n\n3, 2, 1, 6 on diminished chords\n\n(Works best with cyclical progression e.g II-V-I)",
    descriptionZh: "Voice Led 声部连接\n\n小调和弦：1, 3, 5, 7\n\n属和弦：3, 5, 7, 2\n\n大调和弦：3, 2, 1, 7\n\n挂留和弦：4, 5, 7, 2\n\n减和弦：3, 2, 1, 6\n\n（最适合循环进行，如 II-V-I）",
    groupName: "Voice Led Structures",
    groupNameZh: "Voice Led 声部连接",
    sequences: {
      dominant: [3, 5, 7, 2],
      major: [3, 2, 1, 7],
      minor: [1, 3, 5, 7],
      sus: [4, 5, 7, 2],
      diminished: [3, 2, 1, 7],
      diminishedDominant: [4, 6, 8, 2],
      six: [3, 5, 7, 2],
      augmented: [4, 6, 7, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
  {
    id: "voice_led_structure_5",
    nameKey: "level_voice_led_5",
    name: "Voice Led Structure 5",
    nameZh: "Voice Led 结构 5",
    description: "Voice led structures\n\n5, 3, 1, 7 on minor chords\n\n3, 5, 7, 2 on dominant chords\n\n3, 2, 1, 7 on major chords\n\n4, 5, 7, 2 on sus chords\n\n3, 2, 1, 6 on diminished chords\n\n(Works best with cyclical progression e.g II-V-I)",
    descriptionZh: "Voice Led 声部连接\n\n小调和弦：5, 3, 1, 7\n\n属和弦：3, 5, 7, 2\n\n大调和弦：3, 2, 1, 7\n\n挂留和弦：4, 5, 7, 2\n\n减和弦：3, 2, 1, 6\n\n（最适合循环进行，如 II-V-I）",
    groupName: "Voice Led Structures",
    groupNameZh: "Voice Led 声部连接",
    sequences: {
      dominant: [3, 5, 7, 2],
      major: [3, 2, 1, 7],
      minor: [5, 3, 1, 7],
      sus: [4, 5, 7, 2],
      diminished: [3, 2, 1, 7],
      diminishedDominant: [4, 6, 8, 2],
      six: [3, 5, 7, 2],
      augmented: [4, 6, 7, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 4,
  },
]

export const SUSPENDED_LEVELS: PracticeLevel[] = [
  {
    id: "suspended_2_resolution",
    nameKey: "level_suspended_2",
    name: "Suspended 2 Resolution",
    nameZh: "挂二解决",
    description: "Suspended Structures\n\nSuspended 2 resolving to 3 then 1",
    descriptionZh: "挂留结构\n\n挂二解决到三音再到根音",
    groupName: "Suspended Structures",
    groupNameZh: "挂留结构",
    sequences: {
      dominant: [2, 3, 1],
      major: [2, 3, 1],
      minor: [2, 3, 1],
      sus: [2, 3, 1],
      diminished: [2, 3, 1],
      diminishedDominant: [2, 4, 1],
      six: [2, 3, 1],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 3,
  },
  {
    id: "suspended_4_resolution",
    nameKey: "level_suspended_4",
    name: "Suspended 4 Resolution",
    nameZh: "挂四解决",
    description: "Suspended Structures\n\nSuspended 4 resolving to 3 then 1",
    descriptionZh: "挂留结构\n\n挂四解决到三音再到根音",
    groupName: "Suspended Structures",
    groupNameZh: "挂留结构",
    sequences: {
      dominant: [4, 3, 1],
      major: [4, 3, 1],
      minor: [4, 3, 1],
      sus: [4, 3, 1],
      diminished: [4, 3, 1],
      diminishedDominant: [5, 4, 1],
      six: [4, 3, 1],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: false,
    randomOption: false,
    forceNaturalFive: true,
    notesPerChord: 3,
  },
]

export const CHORD_SCALES_LEVELS: PracticeLevel[] = [
  {
    id: "chord_scale",
    nameKey: "level_chord_scale",
    name: "Chord Scale",
    nameZh: "和弦音阶",
    description: "All notes of the relevant chord scale played from the root note through one octave",
    descriptionZh: "从根音开始演奏一个八度的完整和弦音阶",
    groupName: "Chord Scales",
    groupNameZh: "和弦音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7],
      major: [1, 2, 3, 4, 5, 6, 7],
      minor: [1, 2, 3, 4, 5, 6, 7],
      sus: [1, 2, 3, 4, 5, 6, 7],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 3, 4, 5, 6, 7, 8],
      six: [1, 2, 3, 4, 5, 6, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "chord_scale_3rd_to_3rd",
    nameKey: "level_chord_scale_3rd",
    name: "Chord Scale (3rd to 3rd)",
    nameZh: "和弦音阶（三音到三音）",
    description: "All notes of the relevant chord scale played from the 3rd through one octave",
    descriptionZh: "从三音开始演奏一个八度的完整和弦音阶",
    groupName: "Chord Scales",
    groupNameZh: "和弦音阶",
    sequences: {
      dominant: [3, 4, 5, 6, 7, 1, 2],
      major: [3, 4, 5, 6, 7, 1, 2],
      minor: [3, 4, 5, 6, 7, 1, 2],
      sus: [4, 5, 6, 7, 1, 2, 3],
      diminished: [3, 4, 5, 6, 7, 8, 1, 2],
      diminishedDominant: [4, 5, 6, 7, 8, 1, 2, 3],
      six: [3, 4, 5, 6, 7, 1, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "chord_scale_5th_to_5th",
    nameKey: "level_chord_scale_5th",
    name: "Chord Scale (5th to 5th)",
    nameZh: "和弦音阶（五音到五音）",
    description: "All notes of the relevant chord scale played from the 5th through one octave",
    descriptionZh: "从五音开始演奏一个八度的完整和弦音阶",
    groupName: "Chord Scales",
    groupNameZh: "和弦音阶",
    sequences: {
      dominant: [5, 6, 7, 1, 2, 3, 4],
      major: [5, 6, 7, 1, 2, 3, 4],
      minor: [5, 6, 7, 1, 2, 3, 4],
      sus: [5, 6, 7, 1, 2, 3, 4],
      diminished: [5, 6, 7, 8, 1, 2, 3, 4],
      diminishedDominant: [6, 7, 8, 1, 2, 3, 4, 5],
      six: [5, 6, 7, 1, 2, 3, 4],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "chord_scale_7th_to_7th",
    nameKey: "level_chord_scale_7th",
    name: "Chord Scale (7th to 7th)",
    nameZh: "和弦音阶（七音到七音）",
    description: "All notes of the relevant chord scale played from the 7th through one octave",
    descriptionZh: "从七音开始演奏一个八度的完整和弦音阶",
    groupName: "Chord Scales",
    groupNameZh: "和弦音阶",
    sequences: {
      dominant: [7, 1, 2, 3, 4, 5, 6],
      major: [7, 1, 2, 3, 4, 5, 6],
      minor: [7, 1, 2, 3, 4, 5, 6],
      sus: [7, 1, 2, 3, 4, 5, 6],
      diminished: [8, 1, 2, 3, 4, 5, 6, 7],
      diminishedDominant: [8, 1, 2, 3, 4, 5, 6, 7],
      six: [7, 1, 2, 3, 4, 5, 6],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "chord_scale_random_chord_tone",
    nameKey: "level_chord_scale_random_ct",
    name: "Chord Scale (Random Starting Chord Tone)",
    nameZh: "和弦音阶（随机和弦音起始）",
    description: "All notes of the relevant chord scale starting from a randomised chord tone",
    descriptionZh: "从随机和弦音开始演奏完整和弦音阶",
    groupName: "Chord Scales",
    groupNameZh: "和弦音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7],
      major: [1, 2, 3, 4, 5, 6, 7],
      minor: [1, 2, 3, 4, 5, 6, 7],
      sus: [1, 2, 3, 4, 5, 6, 7],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 3, 4, 5, 6, 7, 8],
      six: [1, 2, 3, 4, 5, 6, 7],
    },
    startingIntervalOption: "chordTone",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "chord_scale_random_scale_tone",
    nameKey: "level_chord_scale_random_st",
    name: "Chord Scale (Random Starting Scale Tone)",
    nameZh: "和弦音阶（随机音阶音起始）",
    description: "All notes of the relevant chord scale starting from a randomised scale tone",
    descriptionZh: "从随机音阶音开始演奏完整和弦音阶",
    groupName: "Chord Scales",
    groupNameZh: "和弦音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7],
      major: [1, 2, 3, 4, 5, 6, 7],
      minor: [1, 2, 3, 4, 5, 6, 7],
      sus: [1, 2, 3, 4, 5, 6, 7],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 3, 4, 5, 6, 7, 8],
      six: [1, 2, 3, 4, 5, 6, 7],
    },
    startingIntervalOption: "any",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
]

export const PASSING_NOTE_CHORD_SCALES_LEVELS: PracticeLevel[] = [
  {
    id: "passing_note_scale",
    nameKey: "level_passing_note_scale",
    name: "Passing Note Scale",
    nameZh: "经过音音阶",
    description: "All notes of the relevant chord scale with appropriate passing notes, played from root note to root note. If played starting on a downbeat, all of the subsequent chord tones will also fall on downbeats.",
    descriptionZh: "从根音到根音演奏带有适当经过音的完整和弦音阶。如果在强拍开始，后续所有和弦音也将落在强拍上。",
    groupName: "Passing Note Chord Scales",
    groupNameZh: "经过音和弦音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7, 8],
      major: [1, 2, 3, 4, 5, 6, 7, 8],
      minor: [1, 2, 3, 4, 5, 6, 7, 8],
      sus: [1, 2, 3, 4, 5, 6, 7, 8],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 3, 4, 5, 6, 7, 8],
      six: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    usePassingNoteBebopScale: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "passing_note_scale_3rd_to_3rd",
    nameKey: "level_passing_note_scale_3rd",
    name: "Passing Note Scale 3rd to 3rd",
    nameZh: "经过音音阶（三音到三音）",
    description: "All notes of the relevant chord scale with appropriate passing notes, played from 3rd to 3rd. If played starting on a downbeat, all of the subsequent chord tones will also fall on downbeats.",
    descriptionZh: "从三音到三音演奏带有适当经过音的完整和弦音阶。如果在强拍开始，后续所有和弦音也将落在强拍上。",
    groupName: "Passing Note Chord Scales",
    groupNameZh: "经过音和弦音阶",
    sequences: {
      dominant: [3, 4, 5, 6, 7, 8, 1, 2],
      major: [3, 4, 5, 6, 7, 8, 1, 2],
      minor: [3, 4, 5, 6, 7, 8, 1, 2],
      sus: [4, 5, 6, 7, 8, 1, 2, 3],
      diminished: [3, 4, 5, 6, 7, 8, 1, 2],
      diminishedDominant: [4, 5, 6, 7, 8, 1, 2, 3],
      six: [3, 4, 5, 6, 7, 8, 1, 2],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    usePassingNoteBebopScale: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "passing_note_scale_5th_to_5th",
    nameKey: "level_passing_note_scale_5th",
    name: "Passing Note Scale 5th to 5th",
    nameZh: "经过音音阶（五音到五音）",
    description: "All notes of the relevant chord scale with appropriate passing notes, played from 5th to 5th. If played starting on a downbeat, all of the subsequent chord tones will also fall on downbeats.",
    descriptionZh: "从五音到五音演奏带有适当经过音的完整和弦音阶。如果在强拍开始，后续所有和弦音也将落在强拍上。",
    groupName: "Passing Note Chord Scales",
    groupNameZh: "经过音和弦音阶",
    sequences: {
      dominant: [5, 6, 7, 8, 1, 2, 3, 4],
      major: [5, 6, 7, 8, 1, 2, 3, 4],
      minor: [5, 6, 7, 8, 1, 2, 3, 4],
      sus: [5, 6, 7, 8, 1, 2, 3, 4],
      diminished: [5, 6, 7, 8, 1, 2, 3, 4],
      diminishedDominant: [6, 7, 8, 1, 2, 3, 4, 5],
      six: [5, 6, 7, 8, 1, 2, 3, 4],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    usePassingNoteBebopScale: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "passing_note_scale_6th_7th_to_6th_7th",
    nameKey: "level_passing_note_scale_6th_7th",
    name: "Passing Note Scale 6th/7th to 6th/7th",
    nameZh: "经过音音阶（六音/七音到六音/七音）",
    description: "All notes of the relevant chord scale with passing notes, played from 6th to 6th or 7th to 7th, as harmonicaly appopriate. If played starting on a downbeat all of the subsequent chord tones will also fall on downbeats.",
    descriptionZh: "从六音到六音或七音到七音演奏带有经过音的完整和弦音阶（根据和声适当选择）。如果在强拍开始，后续所有和弦音也将落在强拍上。",
    groupName: "Passing Note Chord Scales",
    groupNameZh: "经过音和弦音阶",
    sequences: {
      dominant: [7, 8, 1, 2, 3, 4, 5, 6],
      major: [7, 8, 1, 2, 3, 4, 5, 6],
      minor: [7, 8, 1, 2, 3, 4, 5, 6],
      sus: [7, 8, 1, 2, 3, 4, 5, 6],
      diminished: [7, 8, 1, 2, 3, 4, 5, 6],
      diminishedDominant: [8, 1, 2, 3, 4, 5, 6, 7],
      six: [7, 8, 1, 2, 3, 4, 5, 6],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    usePassingNoteBebopScale: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
  {
    id: "passing_note_scale_random_chord_tone",
    nameKey: "level_passing_note_scale_random_ct",
    name: "Passing Note Scale (Random Starting Chord Tone)",
    nameZh: "经过音音阶（随机和弦音起始）",
    description: "All notes of the relevant chord scale with appropriate passing notes, from a randomised starting chord tone. If played starting on a downbeat, all of the subsequent chord tones will also fall on downbeats.",
    descriptionZh: "从随机和弦音开始演奏带有适当经过音的完整和弦音阶。如果在强拍开始，后续所有和弦音也将落在强拍上。",
    groupName: "Passing Note Chord Scales",
    groupNameZh: "经过音和弦音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7, 8],
      major: [1, 2, 3, 4, 5, 6, 7, 8],
      minor: [1, 2, 3, 4, 5, 6, 7, 8],
      sus: [1, 2, 3, 4, 5, 6, 7, 8],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 3, 4, 5, 6, 7, 8],
      six: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    startingIntervalOption: "chordTone",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    usePassingNoteBebopScale: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
]

export const ALTERED_LEVELS: PracticeLevel[] = [
  {
    id: "altered_dominant_flat9",
    nameKey: "level_altered_flat9",
    name: "Altered Dominant (♭9)",
    nameZh: "变化属和弦（♭9）",
    description: "Altered dominant structures\n\n♭9, 3, ♯9, 7 on dominant chords\n\nWorks with altered dominant chords",
    descriptionZh: "变化属和弦结构\n\n属和弦：♭9, 3, ♯9, 7\n\n适用于变化属和弦",
    groupName: "Altered Dominant Structures",
    groupNameZh: "变化属和弦结构",
    sequences: {
      dominant: [2, 3, 4, 7],
      major: [2, 3, 4, 7],
      minor: [2, 3, 4, 7],
      sus: [2, 4, 5, 7],
      diminished: [2, 3, 4, 7],
      diminishedDominant: [2, 4, 5, 8],
      six: [2, 3, 4, 7],
      altered: [2, 3, 4, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "altered_dominant_sharp9",
    nameKey: "level_altered_sharp9",
    name: "Altered Dominant (♯9)",
    nameZh: "变化属和弦（♯9）",
    description: "Altered dominant structures\n\n♯9, 3, ♭9, 7 on dominant chords\n\nWorks with altered dominant chords",
    descriptionZh: "变化属和弦结构\n\n属和弦：♯9, 3, ♭9, 7\n\n适用于变化属和弦",
    groupName: "Altered Dominant Structures",
    groupNameZh: "变化属和弦结构",
    sequences: {
      dominant: [4, 3, 2, 7],
      major: [4, 3, 2, 7],
      minor: [4, 3, 2, 7],
      sus: [5, 4, 2, 7],
      diminished: [4, 3, 2, 7],
      diminishedDominant: [5, 4, 2, 8],
      six: [4, 3, 2, 7],
      altered: [4, 3, 2, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "altered_dominant_flat5",
    nameKey: "level_altered_flat5",
    name: "Altered Dominant (♭5)",
    nameZh: "变化属和弦（♭5）",
    description: "Altered dominant structures\n\n1, 3, ♭5, 7 on dominant chords\n\nWorks with altered dominant chords",
    descriptionZh: "变化属和弦结构\n\n属和弦：1, 3, ♭5, 7\n\n适用于变化属和弦",
    groupName: "Altered Dominant Structures",
    groupNameZh: "变化属和弦结构",
    sequences: {
      dominant: [1, 3, 6, 7],
      major: [1, 3, 5, 7],
      minor: [1, 3, 5, 7],
      sus: [1, 4, 5, 7],
      diminished: [1, 3, 5, 7],
      diminishedDominant: [1, 4, 6, 8],
      six: [1, 3, 5, 6],
      altered: [1, 3, 6, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "altered_dominant_sharp5",
    nameKey: "level_altered_sharp5",
    name: "Altered Dominant (♯5)",
    nameZh: "变化属和弦（♯5）",
    description: "Altered dominant structures\n\n1, 3, ♯5, 7 on dominant chords\n\nWorks with altered dominant chords",
    descriptionZh: "变化属和弦结构\n\n属和弦：1, 3, ♯5, 7\n\n适用于变化属和弦",
    groupName: "Altered Dominant Structures",
    groupNameZh: "变化属和弦结构",
    sequences: {
      dominant: [1, 3, 6, 7],
      major: [1, 3, 5, 7],
      minor: [1, 3, 5, 7],
      sus: [1, 4, 5, 7],
      diminished: [1, 3, 5, 7],
      diminishedDominant: [1, 4, 6, 8],
      six: [1, 3, 5, 6],
      altered: [1, 3, 6, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 4,
  },
  {
    id: "altered_dominant_full",
    nameKey: "level_altered_full",
    name: "Altered Dominant (Full)",
    nameZh: "变化属和弦（完整）",
    description: "Altered dominant structures\n\n1, 3, ♭5, ♯5, ♭9, ♯9, 7 on dominant chords\n\nWorks with altered dominant chords",
    descriptionZh: "变化属和弦结构\n\n属和弦：1, 3, ♭5, ♯5, ♭9, ♯9, 7\n\n适用于变化属和弦",
    groupName: "Altered Dominant Structures",
    groupNameZh: "变化属和弦结构",
    sequences: {
      dominant: [1, 3, 6, 6, 2, 4, 7],
      major: [1, 3, 5, 6, 2, 4, 7],
      minor: [1, 3, 5, 6, 2, 4, 7],
      sus: [1, 4, 5, 6, 2, 5, 7],
      diminished: [1, 3, 5, 6, 2, 4, 7],
      diminishedDominant: [1, 4, 6, 7, 2, 5, 8],
      six: [1, 3, 5, 6, 2, 4, 6],
      altered: [1, 3, 6, 6, 2, 4, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: false,
    orderOption: true,
    randomOption: true,
    forceNaturalFive: false,
    notesPerChord: 7,
  },
  {
    id: "altered_scale",
    nameKey: "level_altered_scale",
    name: "Altered Scale",
    nameZh: "变化音阶",
    description: "Altered scale (7th mode of melodic minor)\n\n1, ♭2, ♭3, 3, ♭5, ♯5, ♭7\n\nWorks with altered dominant chords",
    descriptionZh: "变化音阶（旋律小调第7调式）\n\n1, ♭2, ♭3, 3, ♭5, ♯5, ♭7\n\n适用于变化属和弦",
    groupName: "Altered Dominant Structures",
    groupNameZh: "变化属和弦结构",
    sequences: {
      dominant: [1, 2, 3, 4, 6, 6, 7],
      major: [1, 2, 3, 4, 6, 6, 7],
      minor: [1, 2, 3, 4, 6, 6, 7],
      sus: [1, 2, 4, 5, 6, 6, 7],
      diminished: [1, 2, 3, 4, 6, 6, 7],
      diminishedDominant: [1, 2, 4, 5, 7, 7, 8],
      six: [1, 2, 3, 4, 6, 6, 7],
      altered: [1, 2, 3, 4, 6, 6, 7],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 8,
  },
]

export const DIMINISHED_SCALES_LEVELS: PracticeLevel[] = [
  {
    id: "diminished_whole_half",
    nameKey: "level_dim_wh",
    name: "Diminished (Whole-Half)",
    nameZh: "减音阶（全半）",
    description: "Diminished whole-half scale\n\n1, 2, ♭3, 4, ♭5, ♭6, 6, 7\n\nWorks with diminished chords",
    descriptionZh: "减音阶（全半）\n\n1, 2, ♭3, 4, ♭5, ♭6, 6, 7\n\n适用于减和弦",
    groupName: "Diminished Scales",
    groupNameZh: "减音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7, 8],
      major: [1, 2, 3, 4, 5, 6, 7, 8],
      minor: [1, 2, 3, 4, 5, 6, 7, 8],
      sus: [1, 2, 4, 5, 5, 6, 7, 8],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 4, 5, 6, 7, 8, 9],
      six: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 9,
  },
  {
    id: "diminished_half_whole",
    nameKey: "level_dim_hw",
    name: "Diminished (Half-Whole)",
    nameZh: "减音阶（半全）",
    description: "Diminished half-whole scale\n\n1, ♭2, ♭3, 3, ♯4, 5, 6, ♭7\n\nWorks with dominant 7♭9 chords",
    descriptionZh: "减音阶（半全）\n\n1, ♭2, ♭3, 3, ♯4, 5, 6, ♭7\n\n适用于属7♭9和弦",
    groupName: "Diminished Scales",
    groupNameZh: "减音阶",
    sequences: {
      dominant: [1, 2, 3, 4, 5, 6, 7, 8],
      major: [1, 2, 3, 4, 5, 6, 7, 8],
      minor: [1, 2, 3, 4, 5, 6, 7, 8],
      sus: [1, 2, 4, 5, 5, 6, 7, 8],
      diminished: [1, 2, 3, 4, 5, 6, 7, 8],
      diminishedDominant: [1, 2, 4, 5, 6, 7, 8, 9],
      six: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    startingIntervalOption: "first",
    takeStartingIntervalBeforeOrder: true,
    endOnStartingInterval: true,
    orderOption: true,
    randomOption: false,
    forceNaturalFive: false,
    notesPerChord: 9,
  },
]

export const ALL_PRACTICE_LEVELS: PracticeLevel[] = [
  ...SINGLE_CHORD_TONES_LEVELS,
  ...TWO_CHORD_TONES_LEVELS,
  ...THREE_CHORD_TONES_LEVELS,
  ...FOUR_CHORD_TONES_LEVELS,
  ...MELODIC_ROOT_TO_5TH_LEVELS,
  ...MELODIC_5TH_TO_9TH_LEVELS,
  ...VOICE_LED_LEVELS,
  ...SUSPENDED_LEVELS,
  ...CHORD_SCALES_LEVELS,
  ...PASSING_NOTE_CHORD_SCALES_LEVELS,
  ...ALTERED_LEVELS,
  ...DIMINISHED_SCALES_LEVELS,
]

export const PRACTICE_MODE_GROUPS = [
  { id: 'single_chord_tones', name: 'Single Chord Tones', nameZh: '单和弦音', levels: SINGLE_CHORD_TONES_LEVELS },
  { id: 'two_chord_tones', name: 'Two Chord Tones', nameZh: '双和弦音', levels: TWO_CHORD_TONES_LEVELS },
  { id: 'three_chord_tones', name: 'Three Chord Tones', nameZh: '三和弦音', levels: THREE_CHORD_TONES_LEVELS },
  { id: 'four_chord_tones', name: 'Four Chord Tones', nameZh: '四和弦音', levels: FOUR_CHORD_TONES_LEVELS },
  { id: 'melodic_root_to_5th', name: 'Melodic Structures - Root to 5th', nameZh: '旋律结构 - 根音到五音', levels: MELODIC_ROOT_TO_5TH_LEVELS },
  { id: 'melodic_5th_to_9th', name: 'Melodic Structures - 5th to 9th', nameZh: '旋律结构 - 五音到九音', levels: MELODIC_5TH_TO_9TH_LEVELS },
  { id: 'voice_led', name: 'Voice Led Structures', nameZh: 'Voice Led 声部连接', levels: VOICE_LED_LEVELS },
  { id: 'suspended', name: 'Suspended Structures', nameZh: '挂留结构', levels: SUSPENDED_LEVELS },
  { id: 'chord_scales', name: 'Chord Scales', nameZh: '和弦音阶', levels: CHORD_SCALES_LEVELS },
  { id: 'passing_note_chord_scales', name: 'Passing Note Chord Scales', nameZh: '经过音和弦音阶', levels: PASSING_NOTE_CHORD_SCALES_LEVELS },
  { id: 'altered', name: 'Altered Dominant Structures', nameZh: '变化属和弦结构', levels: ALTERED_LEVELS },
  { id: 'diminished_scales', name: 'Diminished Scales', nameZh: '减音阶', levels: DIMINISHED_SCALES_LEVELS },
]

export function getPracticeLevelById(id: string): PracticeLevel | undefined {
  return ALL_PRACTICE_LEVELS.find(level => level.id === id)
}

export function getPracticeLevelsByGroup(groupId: string): PracticeLevel[] {
  const group = PRACTICE_MODE_GROUPS.find(g => g.id === groupId)
  return group ? group.levels : []
}