/**
 * iReal Pro 的 `irealbook://` URL 解析。
 *
 * 基准用例直接取自官方格式文档 https://www.irealpro.com/ireal-pro-file-format/
 * 与 PyRealPro 的输出示例，而不是自己编的字符串 —— 这样可以确认我们理解的是
 * 真实格式，而不是"看起来像"的格式。
 */
import { describe, it, expect } from 'vitest'
import {
  parseIrealUrl,
  extractIrealChords,
  irealQualityToProjectType,
} from '@/lib/song-chords'

// 官方文档给出的示例（注意：原文就是未做百分号编码的明文）
const OFFICIAL = 'irealbook://Song Title=LastName FirstName=Style=Ab=n=T44*A{C^7 |A-7 |D-9 |G7#5 }'

// PyRealPro 生成的示例（已做百分号编码，含 staff text 与多种记号）
const PYREALPRO =
  'irealbook://Automation%20Blues=Matonne%20Otto=New%20Orleans%20Swing=G=n=%7BT44%3CGenerated%20by%20pyrealpro%3EG7%20%20%20%7CG7%20%20%20%7CG7%20%20%20%7CG7%20%20%20%5D%5BC7%20%20%20%7CC7%20%20%20%7CG7%20%20%20%7CG7%20%20%20%5D%5BD7%20%20%20%7CC7%20%20%20%7CN1G7%20%20%20%7CD7%20%20%20%7DN2G7%20%20%20%7CG7%20%20%20Z'

describe('parseIrealUrl —— 官方文档示例', () => {
  const song = parseIrealUrl(OFFICIAL)

  it('解析出 6 个字段中的前 4 个（第 5 个是废弃占位）', () => {
    expect(song).not.toBeNull()
    expect(song!.title).toBe('Song Title')
    expect(song!.composer).toBe('LastName FirstName')
    expect(song!.style).toBe('Style')
    expect(song!.key).toBe('Ab')
  })

  it('和弦进行解析成项目内部类型（C^7→Maj7 / A-7→m7 / D-9→m9 / G7#5→7#5）', () => {
    expect(song!.chords).toEqual([
      { root: 'C', type: 'Maj7' },
      { root: 'A', type: 'm7' },
      { root: 'D', type: 'm9' },
      { root: 'G', type: '7#5' },
    ])
  })
})

describe('parseIrealUrl —— PyRealPro 示例（百分号编码）', () => {
  const song = parseIrealUrl(PYREALPRO)

  it('先做 URL 解码再取字段', () => {
    expect(song).not.toBeNull()
    expect(song!.title).toBe('Automation Blues')
    expect(song!.composer).toBe('Matonne Otto')
    expect(song!.style).toBe('New Orleans Swing')
    expect(song!.key).toBe('G')
  })

  it('和弦序列正确，且记号/文本没被误当成和弦', () => {
    expect(song!.chords.map((c) => `${c.root}${c.type === 'Major' ? '' : c.type}`)).toEqual([
      'G7', 'G7', 'G7', 'G7',
      'C7', 'C7', 'G7', 'G7',
      'D7', 'C7', 'G7', 'D7',
      'G7', 'G7',
    ])
  })

  it('staff text「Generated by pyrealpro」不会被解析成 G 和弦', () => {
    // 若没先剥掉 <...>，开头的 "Generated" 会被当成 G 开头的和弦
    expect(song!.chords.every((c) => c.root === 'G' || c.root === 'C' || c.root === 'D')).toBe(true)
    expect(song!.chords.length).toBe(14) // 文本被误解析的话这里会多出几个
  })
})

describe('parseIrealUrl —— 输入校验', () => {
  it('非 iReal URL 返回 null（调用方据此回退到纯文本解析）', () => {
    expect(parseIrealUrl('C | Am | Dm | G7')).toBeNull()
    expect(parseIrealUrl('irealb://C=Am=Dm')).toBeNull() // 另一个前缀，不在支持范围
    expect(parseIrealUrl('')).toBeNull()
  })

  it('字段数不足 6 个返回 null', () => {
    expect(parseIrealUrl('irealbook://Title=Composer=Style=C=n')).toBeNull()
  })

  it('落单的 % 不会抛异常（手工粘贴的 URL 很常见）', () => {
    const song = parseIrealUrl('irealbook://Ti%tle=C=S=Ab=n=T44{C |G7 }')
    expect(song).not.toBeNull()
    expect(song!.title).toBe('Ti%tle')
  })
})

describe('extractIrealChords —— 记号剥离', () => {
  it('拍号 / 排练记号 / 小节线 / 结束标记 / 反复记号都不产生和弦', () => {
    // T44 拍号、*A 排练记号、{ } [ ] 反复、N1/N2 结束标记、Z 终止、Y 留白、<> 文本
    const chords = extractIrealChords('T34*V{<1x>C^7 [A-7 ]|D-9 N1G7 }N2G7 Z YY')
    expect(chords).toEqual([
      { root: 'C', type: 'Maj7' },
      { root: 'A', type: 'm7' },
      { root: 'D', type: 'm9' },
      { root: 'G', type: '7' },
      { root: 'G', type: '7' },
    ])
  })

  it('空进行返回空数组', () => {
    expect(extractIrealChords('')).toEqual([])
    expect(extractIrealChords('T44|{ }[Z')).toEqual([])
  })
})

describe('irealQualityToProjectType —— 质量记号映射', () => {
  it.each([
    ['', 'Major'],
    ['^', 'Major'],
    ['^7', 'Maj7'],
    ['^9', 'Maj9'],
    ['-', 'Minor'],
    ['-7', 'm7'],
    ['-9', 'm9'],
    ['-^7', 'mMaj7'],
    ['h', 'm7b5'],
    ['h7', 'm7b5'],
    ['h9', 'm9b5'],
    ['ø7', 'm7b5'],
    ['o', 'Dim'],
    ['o7', 'dim7'],
    ['+', 'Aug'],
    ['+7', 'aug7'],
    ['7', '7'],
    ['6/9', '6add9'],
    ['7#5', '7#5'],
    ['7b9', '7b9'],
    ['sus', 'sus4'],
    ['7sus', '7sus4'],
    ['9sus', '9sus4'],
    ['madd9', 'madd9'],
  ])('%s → %s', (input, expected) => {
    expect(irealQualityToProjectType(input)).toBe(expected)
  })

  it('映射结果必须是「显示层真的认识的键」，否则界面上会退回原文', () => {
    // 这里是防回归的关键：DISPLAY_NAMES.*.chordTypes 里存在的键才翻得出来。
    // '7alt' 项目没有这个键，属于「有意回退原文」，所以单独排除。
    const KNOWN = new Set([
      '6', '7', '9', '11', '13', 'Major', 'Minor', 'Dim', 'Aug', 'm6', 'Maj7', 'm7', 'm7b5',
      'dim7', 'mMaj7', 'aug7', '7b5', '7#5', 'maj7#5', 'Maj9', 'm9', 'm9b5', '7#9', '7b9',
      '7#11', '9#11', 'm11', 'm13', '13b9', '13#11', 'sus2', 'sus4', '7sus4', '9sus4',
      'add9', 'madd9', '6add9', 'm6add9',
    ])
    const inputs = [
      '', '^', '^7', '^9', '-', '-7', '-9', '-11', '-13', '-6', '-^7', 'h', 'h7', 'h9',
      'ø7', 'o', 'o7', '+', '+7', '7', '9', '11', '13', '6', '6/9', '7b5', '7#5', '7b9',
      '7#9', '7#11', '9#11', '13#11', 'sus', 'sus4', 'sus2', '7sus', '7sus4', '9sus',
      '9sus4', 'add9', 'madd9', 'm6/9',
    ]
    for (const q of inputs) {
      const mapped = irealQualityToProjectType(q)
      expect(KNOWN.has(mapped), `「${q}」映射成了 ${mapped}，显示层不认识`).toBe(true)
    }
  })
})
